/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AlarmSummary_H_
#define	_AlarmSummary_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include "Unsigned8.h"
#include "EC-State.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlarmSummary__unacknowledgedState {
	AlarmSummary__unacknowledgedState_none	= 0,
	AlarmSummary__unacknowledgedState_active	= 1,
	AlarmSummary__unacknowledgedState_idle	= 2,
	AlarmSummary__unacknowledgedState_both	= 3
} e_AlarmSummary__unacknowledgedState;

/* Forward declarations */
struct EventTime;

/* AlarmSummary */
typedef struct AlarmSummary {
	ObjectName_t	 eventConditionName;
	Unsigned8_t	 severity;
	EC_State_t	 currentState;
	long	 unacknowledgedState;
	struct EventTime	*timeOfLastTransitionToActive	/* OPTIONAL */;
	struct EventTime	*timeOfLastTransitionToIdle	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlarmSummary_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlarmSummary;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EventTime.h"

#endif	/* _AlarmSummary_H_ */
#include <asn_internal.h>
