/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AlarmEnrollmentSummary_H_
#define	_AlarmEnrollmentSummary_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include "Unsigned8.h"
#include "EC-State.h"
#include <BOOLEAN.h>
#include "AlarmAckRule.h"
#include "EE-State.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EventTime;

/* AlarmEnrollmentSummary */
typedef struct AlarmEnrollmentSummary {
	ObjectName_t	 eventEnrollmentName;
	Unsigned8_t	 severity;
	EC_State_t	 currentState;
	BOOLEAN_t	*notificationLost	/* DEFAULT FALSE */;
	AlarmAckRule_t	*alarmAcknowledgmentRule	/* OPTIONAL */;
	EE_State_t	*enrollementState	/* OPTIONAL */;
	struct EventTime	*timeOfLastTransitionToActive	/* OPTIONAL */;
	struct EventTime	*timeActiveAcknowledged	/* OPTIONAL */;
	struct EventTime	*timeOfLastTransitionToIdle	/* OPTIONAL */;
	struct EventTime	*timeIdleAcknowledged	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlarmEnrollmentSummary_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlarmEnrollmentSummary;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EventTime.h"

#endif	/* _AlarmEnrollmentSummary_H_ */
#include <asn_internal.h>
