/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../../../../utils/mms-simple.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AlternateAccess.h"

static asn_TYPE_member_t asn_MBR_indexRange_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct selectAlternateAccess__accessSelection__indexRange, lowIndex),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lowIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct selectAlternateAccess__accessSelection__indexRange, numberOfElements),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfElements"
		},
};
static const ber_tlv_tag_t asn_DEF_indexRange_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_indexRange_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lowIndex */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* numberOfElements */
};
static asn_SEQUENCE_specifics_t asn_SPC_indexRange_specs_7 = {
	sizeof(struct selectAlternateAccess__accessSelection__indexRange),
	offsetof(struct selectAlternateAccess__accessSelection__indexRange, _asn_ctx),
	asn_MAP_indexRange_tag2el_7,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_indexRange_7 = {
	"indexRange",
	"indexRange",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_indexRange_tags_7,
	sizeof(asn_DEF_indexRange_tags_7)
		/sizeof(asn_DEF_indexRange_tags_7[0]) - 1, /* 1 */
	asn_DEF_indexRange_tags_7,	/* Same as above */
	sizeof(asn_DEF_indexRange_tags_7)
		/sizeof(asn_DEF_indexRange_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_indexRange_7,
	2,	/* Elements count */
	&asn_SPC_indexRange_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_accessSelection_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct selectAlternateAccess__accessSelection, choice.component),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"component"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct selectAlternateAccess__accessSelection, choice.index),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct selectAlternateAccess__accessSelection, choice.indexRange),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_indexRange_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"indexRange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct selectAlternateAccess__accessSelection, choice.allElements),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"allElements"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_accessSelection_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* component */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* indexRange */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* allElements */
};
static asn_CHOICE_specifics_t asn_SPC_accessSelection_specs_4 = {
	sizeof(struct selectAlternateAccess__accessSelection),
	offsetof(struct selectAlternateAccess__accessSelection, _asn_ctx),
	offsetof(struct selectAlternateAccess__accessSelection, present),
	sizeof(((struct selectAlternateAccess__accessSelection *)0)->present),
	asn_MAP_accessSelection_tag2el_4,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_accessSelection_4 = {
	"accessSelection",
	"accessSelection",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_accessSelection_4,
	4,	/* Elements count */
	&asn_SPC_accessSelection_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_selectAlternateAccess_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct selectAlternateAccess, accessSelection),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_accessSelection_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessSelection"
		},
	{ ATF_POINTER, 0, offsetof(struct selectAlternateAccess, alternateAccess),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlternateAccess,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alternateAccess"
		},
};
static const ber_tlv_tag_t asn_DEF_selectAlternateAccess_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_selectAlternateAccess_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* alternateAccess */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* component */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* indexRange */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 } /* allElements */
};
static asn_SEQUENCE_specifics_t asn_SPC_selectAlternateAccess_specs_3 = {
	sizeof(struct selectAlternateAccess),
	offsetof(struct selectAlternateAccess, _asn_ctx),
	asn_MAP_selectAlternateAccess_tag2el_3,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_selectAlternateAccess_3 = {
	"selectAlternateAccess",
	"selectAlternateAccess",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_selectAlternateAccess_tags_3,
	sizeof(asn_DEF_selectAlternateAccess_tags_3)
		/sizeof(asn_DEF_selectAlternateAccess_tags_3[0]) - 1, /* 1 */
	asn_DEF_selectAlternateAccess_tags_3,	/* Same as above */
	sizeof(asn_DEF_selectAlternateAccess_tags_3)
		/sizeof(asn_DEF_selectAlternateAccess_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_selectAlternateAccess_3,
	2,	/* Elements count */
	&asn_SPC_selectAlternateAccess_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_named_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct named, componentName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"componentName"
		},
	{ ATF_POINTER, 0, offsetof(struct named, accesst),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_AlternateAccessSelection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accesst"
		},
};
static const ber_tlv_tag_t asn_DEF_named_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_named_tag2el_16[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 1 }, /* componentName */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, -1, 0 }, /* selectAlternateAccess */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* component */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* indexRange */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 } /* allElements */
};
static asn_SEQUENCE_specifics_t asn_SPC_named_specs_16 = {
	sizeof(struct named),
	offsetof(struct named, _asn_ctx),
	asn_MAP_named_tag2el_16,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_named_16 = {
	"named",
	"named",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_named_tags_16,
	sizeof(asn_DEF_named_tags_16)
		/sizeof(asn_DEF_named_tags_16[0]) - 1, /* 1 */
	asn_DEF_named_tags_16,	/* Same as above */
	sizeof(asn_DEF_named_tags_16)
		/sizeof(asn_DEF_named_tags_16[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_named_16,
	2,	/* Elements count */
	&asn_SPC_named_specs_16	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.selectAlternateAccess),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_selectAlternateAccess_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"selectAlternateAccess"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.component),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"component"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.index),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.indexRange),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IndexRangeSeq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"indexRange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.allElements),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"allElements"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlternateAccess__Member, choice.named),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_named_16,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"named"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* selectAlternateAccess */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* component */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* indexRange */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* allElements */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* named */
};
static asn_CHOICE_specifics_t asn_SPC_Member_specs_2 = {
	sizeof(struct AlternateAccess__Member),
	offsetof(struct AlternateAccess__Member, _asn_ctx),
	offsetof(struct AlternateAccess__Member, present),
	sizeof(((struct AlternateAccess__Member *)0)->present),
	asn_MAP_Member_tag2el_2,
	6,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_2 = {
	"CHOICE",
	"CHOICE",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Member_2,
	6,	/* Elements count */
	&asn_SPC_Member_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_AlternateAccess_1[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Member_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_AlternateAccess_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_AlternateAccess_specs_1 = {
	sizeof(struct AlternateAccess),
	offsetof(struct AlternateAccess, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
asn_TYPE_descriptor_t asn_DEF_AlternateAccess = {
	"AlternateAccess",
	"AlternateAccess",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AlternateAccess_tags_1,
	sizeof(asn_DEF_AlternateAccess_tags_1)
		/sizeof(asn_DEF_AlternateAccess_tags_1[0]), /* 1 */
	asn_DEF_AlternateAccess_tags_1,	/* Same as above */
	sizeof(asn_DEF_AlternateAccess_tags_1)
		/sizeof(asn_DEF_AlternateAccess_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AlternateAccess_1,
	1,	/* Single element */
	&asn_SPC_AlternateAccess_specs_1	/* Additional specs */
};

