/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AlterEventConditionMonitoring_Request_H_
#define	_AlterEventConditionMonitoring_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include <BOOLEAN.h>
#include "Priority.h"
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlterEventConditionMonitoring-Request */
typedef struct AlterEventConditionMonitoring_Request {
	ObjectName_t	 eventConditionName;
	BOOLEAN_t	*enabled	/* OPTIONAL */;
	Priority_t	*priority	/* OPTIONAL */;
	BOOLEAN_t	*alarmSummaryReports	/* OPTIONAL */;
	Unsigned32_t	*evaluationInterval	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlterEventConditionMonitoring_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlterEventConditionMonitoring_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _AlterEventConditionMonitoring_Request_H_ */
#include <asn_internal.h>
