/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AlterEventEnrollment_Response_H_
#define	_AlterEventEnrollment_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EventTime.h"
#include "EE-State.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlterEventEnrollment_Response__currentState_PR {
	AlterEventEnrollment_Response__currentState_PR_NOTHING,	/* No components present */
	AlterEventEnrollment_Response__currentState_PR_state,
	AlterEventEnrollment_Response__currentState_PR_undefined
} AlterEventEnrollment_Response__currentState_PR;

/* AlterEventEnrollment-Response */
typedef struct AlterEventEnrollment_Response {
	struct AlterEventEnrollment_Response__currentState {
		AlterEventEnrollment_Response__currentState_PR present;
		union AlterEventEnrollment_Response__currentState_u {
			EE_State_t	 state;
			NULL_t	 undefined;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} currentState;
	EventTime_t	 transitionTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlterEventEnrollment_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlterEventEnrollment_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _AlterEventEnrollment_Response_H_ */
#include <asn_internal.h>
