/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Conclude_ResponsePDU_H_
#define	_Conclude_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Conclude-ResponsePDU */
typedef NULL_t	 Conclude_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Conclude_ResponsePDU;
asn_struct_free_f Conclude_ResponsePDU_free;
asn_struct_print_f Conclude_ResponsePDU_print;
asn_constr_check_f Conclude_ResponsePDU_constraint;
ber_type_decoder_f Conclude_ResponsePDU_decode_ber;
der_type_encoder_f Conclude_ResponsePDU_encode_der;
xer_type_decoder_f Conclude_ResponsePDU_decode_xer;
xer_type_encoder_f Conclude_ResponsePDU_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Conclude_ResponsePDU_H_ */
#include <asn_internal.h>
