/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "Confirmed-RequestPDU.h"

static asn_TYPE_member_t asn_MBR_listOfModifier_3[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Modifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listOfModifier_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfModifier_specs_3 = {
	sizeof(struct Confirmed_RequestPDU__listOfModifier),
	offsetof(struct Confirmed_RequestPDU__listOfModifier, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfModifier_3 = {
	"listOfModifier",
	"listOfModifier",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfModifier_tags_3,
	sizeof(asn_DEF_listOfModifier_tags_3)
		/sizeof(asn_DEF_listOfModifier_tags_3[0]), /* 1 */
	asn_DEF_listOfModifier_tags_3,	/* Same as above */
	sizeof(asn_DEF_listOfModifier_tags_3)
		/sizeof(asn_DEF_listOfModifier_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfModifier_3,
	1,	/* Single element */
	&asn_SPC_listOfModifier_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Confirmed_RequestPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Confirmed_RequestPDU, invokeID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"invokeID"
		},
	{ ATF_POINTER, 1, offsetof(struct Confirmed_RequestPDU, listOfModifier),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_listOfModifier_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfModifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Confirmed_RequestPDU, confirmedServiceRequest),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ConfirmedServiceRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"confirmedServiceRequest"
		},
	{ ATF_POINTER, 1, offsetof(struct Confirmed_RequestPDU, cs_request_detail),
		(ASN_TAG_CLASS_CONTEXT | (79 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CS_Request_Detail,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cs-request-detail"
		},
};
static const ber_tlv_tag_t asn_DEF_Confirmed_RequestPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Confirmed_RequestPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* invokeID */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* listOfModifier */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* status */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* getNameList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* identify */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* rename */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 2, 0, 0 }, /* read */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* write */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 2, 0, 0 }, /* getVariableAccessAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 2, 0, 0 }, /* defineNamedVariable */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 2, 0, 0 }, /* defineScatteredAccess */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 2, 0, 0 }, /* getScatteredAccessAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 2, 0, 0 }, /* deleteVariableAccess */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 2, 0, 0 }, /* defineNamedVariableList */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 2, 0, 0 }, /* getNamedVariableListAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 2, 0, 0 }, /* deleteNamedVariableList */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 2, 0, 0 }, /* defineNamedType */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 2, 0, 0 }, /* getNamedTypeAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 2, 0, 0 }, /* deleteNamedType */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 2, 0, 0 }, /* input */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 2, 0, 0 }, /* output */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 2, 0, 0 }, /* takeControl */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 2, 0, 0 }, /* relinquishControl */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 2, 0, 0 }, /* defineSemaphore */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 2, 0, 0 }, /* deleteSemaphore */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 2, 0, 0 }, /* reportSemaphoreStatus */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 2, 0, 0 }, /* reportPoolSemaphoreStatus */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 2, 0, 0 }, /* reportSemaphoreEntryStatus */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 2, 0, 0 }, /* initiateDownloadSequence */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 2, 0, 0 }, /* downloadSegment */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 2, 0, 0 }, /* terminateDownloadSequence */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 2, 0, 0 }, /* initiateUploadSequence */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 2, 0, 0 }, /* uploadSegment */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 2, 0, 0 }, /* terminateUploadSequence */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 2, 0, 0 }, /* requestDomainDownload */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 2, 0, 0 }, /* requestDomainUpload */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 2, 0, 0 }, /* loadDomainContent */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 2, 0, 0 }, /* storeDomainContent */
    { (ASN_TAG_CLASS_CONTEXT | (36 << 2)), 2, 0, 0 }, /* deleteDomain */
    { (ASN_TAG_CLASS_CONTEXT | (37 << 2)), 2, 0, 0 }, /* getDomainAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (38 << 2)), 2, 0, 0 }, /* createProgramInvocation */
    { (ASN_TAG_CLASS_CONTEXT | (39 << 2)), 2, 0, 0 }, /* deleteProgramInvocation */
    { (ASN_TAG_CLASS_CONTEXT | (40 << 2)), 2, 0, 0 }, /* start */
    { (ASN_TAG_CLASS_CONTEXT | (41 << 2)), 2, 0, 0 }, /* stop */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 2, 0, 0 }, /* resume */
    { (ASN_TAG_CLASS_CONTEXT | (43 << 2)), 2, 0, 0 }, /* reset */
    { (ASN_TAG_CLASS_CONTEXT | (44 << 2)), 2, 0, 0 }, /* kill */
    { (ASN_TAG_CLASS_CONTEXT | (45 << 2)), 2, 0, 0 }, /* getProgramInvocationAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (46 << 2)), 2, 0, 0 }, /* obtainFile */
    { (ASN_TAG_CLASS_CONTEXT | (47 << 2)), 2, 0, 0 }, /* defineEventCondition */
    { (ASN_TAG_CLASS_CONTEXT | (48 << 2)), 2, 0, 0 }, /* deleteEventCondition */
    { (ASN_TAG_CLASS_CONTEXT | (49 << 2)), 2, 0, 0 }, /* getEventConditionAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (50 << 2)), 2, 0, 0 }, /* reportEventConditionStatus */
    { (ASN_TAG_CLASS_CONTEXT | (51 << 2)), 2, 0, 0 }, /* alterEventConditionMonitoring */
    { (ASN_TAG_CLASS_CONTEXT | (52 << 2)), 2, 0, 0 }, /* triggerEvent */
    { (ASN_TAG_CLASS_CONTEXT | (53 << 2)), 2, 0, 0 }, /* defineEventAction */
    { (ASN_TAG_CLASS_CONTEXT | (54 << 2)), 2, 0, 0 }, /* deleteEventAction */
    { (ASN_TAG_CLASS_CONTEXT | (55 << 2)), 2, 0, 0 }, /* getEventActionAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (56 << 2)), 2, 0, 0 }, /* reportEventActionStatus */
    { (ASN_TAG_CLASS_CONTEXT | (57 << 2)), 2, 0, 0 }, /* defineEventEnrollment */
    { (ASN_TAG_CLASS_CONTEXT | (58 << 2)), 2, 0, 0 }, /* deleteEventEnrollment */
    { (ASN_TAG_CLASS_CONTEXT | (59 << 2)), 2, 0, 0 }, /* alterEventEnrollment */
    { (ASN_TAG_CLASS_CONTEXT | (60 << 2)), 2, 0, 0 }, /* reportEventEnrollmentStatus */
    { (ASN_TAG_CLASS_CONTEXT | (61 << 2)), 2, 0, 0 }, /* getEventEnrollmentAttributes */
    { (ASN_TAG_CLASS_CONTEXT | (62 << 2)), 2, 0, 0 }, /* acknowledgeEventNotification */
    { (ASN_TAG_CLASS_CONTEXT | (63 << 2)), 2, 0, 0 }, /* getAlarmSummary */
    { (ASN_TAG_CLASS_CONTEXT | (64 << 2)), 2, 0, 0 }, /* getAlarmEnrollmentSummary */
    { (ASN_TAG_CLASS_CONTEXT | (65 << 2)), 2, 0, 0 }, /* readJournal */
    { (ASN_TAG_CLASS_CONTEXT | (66 << 2)), 2, 0, 0 }, /* writeJournal */
    { (ASN_TAG_CLASS_CONTEXT | (67 << 2)), 2, 0, 0 }, /* initializeJournal */
    { (ASN_TAG_CLASS_CONTEXT | (68 << 2)), 2, 0, 0 }, /* reportJournalStatus */
    { (ASN_TAG_CLASS_CONTEXT | (69 << 2)), 2, 0, 0 }, /* createJournal */
    { (ASN_TAG_CLASS_CONTEXT | (70 << 2)), 2, 0, 0 }, /* deleteJournal */
    { (ASN_TAG_CLASS_CONTEXT | (71 << 2)), 2, 0, 0 }, /* getCapabilityList */
    { (ASN_TAG_CLASS_CONTEXT | (72 << 2)), 2, 0, 0 }, /* fileOpen */
    { (ASN_TAG_CLASS_CONTEXT | (73 << 2)), 2, 0, 0 }, /* fileRead */
    { (ASN_TAG_CLASS_CONTEXT | (74 << 2)), 2, 0, 0 }, /* fileClose */
    { (ASN_TAG_CLASS_CONTEXT | (75 << 2)), 2, 0, 0 }, /* fileRename */
    { (ASN_TAG_CLASS_CONTEXT | (76 << 2)), 2, 0, 0 }, /* fileDelete */
    { (ASN_TAG_CLASS_CONTEXT | (77 << 2)), 2, 0, 0 }, /* fileDirectory */
    { (ASN_TAG_CLASS_CONTEXT | (79 << 2)), 3, 0, 0 } /* cs-request-detail */
};
static asn_SEQUENCE_specifics_t asn_SPC_Confirmed_RequestPDU_specs_1 = {
	sizeof(struct Confirmed_RequestPDU),
	offsetof(struct Confirmed_RequestPDU, _asn_ctx),
	asn_MAP_Confirmed_RequestPDU_tag2el_1,
	81,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Confirmed_RequestPDU = {
	"Confirmed-RequestPDU",
	"Confirmed-RequestPDU",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Confirmed_RequestPDU_tags_1,
	sizeof(asn_DEF_Confirmed_RequestPDU_tags_1)
		/sizeof(asn_DEF_Confirmed_RequestPDU_tags_1[0]), /* 1 */
	asn_DEF_Confirmed_RequestPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_Confirmed_RequestPDU_tags_1)
		/sizeof(asn_DEF_Confirmed_RequestPDU_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Confirmed_RequestPDU_1,
	4,	/* Elements count */
	&asn_SPC_Confirmed_RequestPDU_specs_1	/* Additional specs */
};

