/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Confirmed_ResponsePDU_H_
#define	_Confirmed_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include "ConfirmedServiceResponse.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CS_Request_Detail;

/* Confirmed-ResponsePDU */
typedef struct Confirmed_ResponsePDU {
	Unsigned32_t	 invokeID;
	ConfirmedServiceResponse_t	 confirmedServiceResponse;
	struct CS_Request_Detail	*cs_request_detail	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Confirmed_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Confirmed_ResponsePDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CS-Request-Detail.h"

#endif	/* _Confirmed_ResponsePDU_H_ */
#include <asn_internal.h>
