/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Confirmed_RequestPDU_H_
#define	_Confirmed_RequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include "ConfirmedServiceRequest.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CS_Request_Detail;
struct Modifier;

/* Confirmed-RequestPDU */
typedef struct Confirmed_RequestPDU {
	Unsigned32_t	 invokeID;
	struct Confirmed_RequestPDU__listOfModifier {
		A_SEQUENCE_OF(struct Modifier) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfModifier;
	ConfirmedServiceRequest_t	 confirmedServiceRequest;
	struct CS_Request_Detail	*cs_request_detail	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Confirmed_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Confirmed_RequestPDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CS-Request-Detail.h"
#include "Modifier.h"

#endif	/* _Confirmed_RequestPDU_H_ */
#include <asn_internal.h>
