/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "CS-Request-Detail.h"

static asn_TYPE_member_t asn_MBR_CS_Request_Detail_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_Request_Detail, choice.foo),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"foo"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CS_Request_Detail_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* foo */
};
static asn_CHOICE_specifics_t asn_SPC_CS_Request_Detail_specs_1 = {
	sizeof(struct CS_Request_Detail),
	offsetof(struct CS_Request_Detail, _asn_ctx),
	offsetof(struct CS_Request_Detail, present),
	sizeof(((struct CS_Request_Detail *)0)->present),
	asn_MAP_CS_Request_Detail_tag2el_1,
	1,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CS_Request_Detail = {
	"CS-Request-Detail",
	"CS-Request-Detail",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_CS_Request_Detail_1,
	1,	/* Elements count */
	&asn_SPC_CS_Request_Detail_specs_1	/* Additional specs */
};

