/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CS_Request_Detail_H_
#define	_CS_Request_Detail_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CS_Request_Detail_PR {
	CS_Request_Detail_PR_NOTHING,	/* No components present */
	CS_Request_Detail_PR_foo
} CS_Request_Detail_PR;

/* CS-Request-Detail */
typedef struct CS_Request_Detail {
	CS_Request_Detail_PR present;
	union CS_Request_Detail_u {
		long	 foo;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CS_Request_Detail_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CS_Request_Detail;

#ifdef __cplusplus
}
#endif

#endif	/* _CS_Request_Detail_H_ */
#include <asn_internal.h>
