/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../../../../utils/mms-simple.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Data_H_
#define	_Data_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include "FloatingPoint.h"
#include <OCTET_STRING.h>
#include <VisibleString.h>
#include "TimeOfDay.h"
#include "MMSString.h"
#include "UtcTime.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Data_PR {
	Data_PR_NOTHING,	/* No components present */
	Data_PR_array,
	Data_PR_structure,
	Data_PR_boolean,
	Data_PR_bitString,
	Data_PR_integer,
	Data_PR_unsigned,
	Data_PR_floatingPoint,
	Data_PR_octetString,
	Data_PR_visibleString,
	Data_PR_binaryTime,
	Data_PR_mmsString,
	Data_PR_utcTime
} Data_PR;

/* Forward declarations */
struct DataSequence;

/* Data */
typedef struct Data {
	Data_PR present;
	union Data_u {
		struct DataSequence	*array;
		struct DataSequence	*structure;
		BOOLEAN_t	 boolean;
		BIT_STRING_t	 bitString;
		long	 integer;
		long	 Unsigned;
		FloatingPoint_t	 floatingPoint;
		OCTET_STRING_t	 octetString;
		VisibleString_t	 visibleString;
		TimeOfDay_t	 binaryTime;
		MMSString_t	 mmsString;
		UtcTime_t	 utcTime;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Data;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DataSequence.h"

#endif	/* _Data_H_ */
#include <asn_internal.h>
