/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../../../../utils/mms-simple.asn"
 * 	`asn1c -fcompound-names`
 */

#include "Data.h"

static asn_TYPE_member_t asn_MBR_Data_1[] = {
	{ ATF_POINTER, 0, offsetof(struct Data, choice.array),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"array"
		},
	{ ATF_POINTER, 0, offsetof(struct Data, choice.structure),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"structure"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.boolean),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"boolean"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.bitString),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.integer),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"integer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.Unsigned),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unsigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.floatingPoint),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FloatingPoint,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"floatingPoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.octetString),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octetString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.visibleString),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"visibleString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.binaryTime),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeOfDay,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"binaryTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.mmsString),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MMSString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mmsString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data, choice.utcTime),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UtcTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"utcTime"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Data_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* array */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* structure */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* boolean */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* bitString */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* floatingPoint */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 7, 0, 0 }, /* octetString */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 8, 0, 0 }, /* visibleString */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 9, 0, 0 }, /* binaryTime */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 10, 0, 0 }, /* mmsString */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 11, 0, 0 } /* utcTime */
};
static asn_CHOICE_specifics_t asn_SPC_Data_specs_1 = {
	sizeof(struct Data),
	offsetof(struct Data, _asn_ctx),
	offsetof(struct Data, present),
	sizeof(((struct Data *)0)->present),
	asn_MAP_Data_tag2el_1,
	12,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Data = {
	"Data",
	"Data",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Data_1,
	12,	/* Elements count */
	&asn_SPC_Data_specs_1	/* Additional specs */
};

