/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DefineNamedType_Request_H_
#define	_DefineNamedType_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include "TypeSpecification.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DefineNamedType-Request */
typedef struct DefineNamedType_Request {
	ObjectName_t	 typeName;
	TypeSpecification_t	 typeSpecification;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineNamedType_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineNamedType_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _DefineNamedType_Request_H_ */
#include <asn_internal.h>
