/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DefineEventEnrollment_Request_H_
#define	_DefineEventEnrollment_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include "Transitions.h"
#include "AlarmAckRule.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;

/* DefineEventEnrollment-Request */
typedef struct DefineEventEnrollment_Request {
	ObjectName_t	 eventEnrollmentName;
	ObjectName_t	 eventConditionName;
	Transitions_t	 eventConditionTransition;
	AlarmAckRule_t	 alarmAcknowledgementRule;
	struct ObjectName	*eventActionName	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineEventEnrollment_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineEventEnrollment_Request;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _DefineEventEnrollment_Request_H_ */
#include <asn_internal.h>
