/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "DefineNamedType-Request.h"

static asn_TYPE_member_t asn_MBR_DefineNamedType_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DefineNamedType_Request, typeName),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"typeName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DefineNamedType_Request, typeSpecification),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_TypeSpecification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"typeSpecification"
		},
};
static const ber_tlv_tag_t asn_DEF_DefineNamedType_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DefineNamedType_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 1 }, /* vmd-specific */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, -1, 0 }, /* typeName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 1 }, /* domain-specific */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, -1, 0 }, /* array */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 1 }, /* aa-specific */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, -1, 0 }, /* structure */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* boolean */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* bit-string */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 1, 0, 0 }, /* unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 1, 0, 0 }, /* octet-string */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 1, 0, 0 }, /* visible-string */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 1, 0, 0 }, /* generalized-time */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 1, 0, 0 }, /* binary-time */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 1, 0, 0 }, /* bcd */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 1, 0, 0 } /* objId */
};
static asn_SEQUENCE_specifics_t asn_SPC_DefineNamedType_Request_specs_1 = {
	sizeof(struct DefineNamedType_Request),
	offsetof(struct DefineNamedType_Request, _asn_ctx),
	asn_MAP_DefineNamedType_Request_tag2el_1,
	16,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DefineNamedType_Request = {
	"DefineNamedType-Request",
	"DefineNamedType-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DefineNamedType_Request_tags_1,
	sizeof(asn_DEF_DefineNamedType_Request_tags_1)
		/sizeof(asn_DEF_DefineNamedType_Request_tags_1[0]), /* 1 */
	asn_DEF_DefineNamedType_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_DefineNamedType_Request_tags_1)
		/sizeof(asn_DEF_DefineNamedType_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DefineNamedType_Request_1,
	2,	/* Elements count */
	&asn_SPC_DefineNamedType_Request_specs_1	/* Additional specs */
};

