/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DefineEventEnrollment_Response_H_
#define	_DefineEventEnrollment_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DefineEventEnrollment-Response */
typedef NULL_t	 DefineEventEnrollment_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineEventEnrollment_Response;
asn_struct_free_f DefineEventEnrollment_Response_free;
asn_struct_print_f DefineEventEnrollment_Response_print;
asn_constr_check_f DefineEventEnrollment_Response_constraint;
ber_type_decoder_f DefineEventEnrollment_Response_decode_ber;
der_type_encoder_f DefineEventEnrollment_Response_encode_der;
xer_type_decoder_f DefineEventEnrollment_Response_decode_xer;
xer_type_encoder_f DefineEventEnrollment_Response_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DefineEventEnrollment_Response_H_ */
#include <asn_internal.h>
