/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DefineNamedVariable_Request_H_
#define	_DefineNamedVariable_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include "Address.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TypeSpecification;

/* DefineNamedVariable-Request */
typedef struct DefineNamedVariable_Request {
	ObjectName_t	 variableName;
	Address_t	 address;
	struct TypeSpecification	*typeSpecification	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineNamedVariable_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineNamedVariable_Request;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TypeSpecification.h"

#endif	/* _DefineNamedVariable_Request_H_ */
#include <asn_internal.h>
