/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DeleteNamedType_Response_H_
#define	_DeleteNamedType_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeleteNamedType-Response */
typedef struct DeleteNamedType_Response {
	Unsigned32_t	 numberMatched;
	Unsigned32_t	 numberDeleted;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeleteNamedType_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeleteNamedType_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _DeleteNamedType_Response_H_ */
#include <asn_internal.h>
