/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DirectoryEntry_H_
#define	_DirectoryEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FileName.h"
#include "FileAttributes.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DirectoryEntry */
typedef struct DirectoryEntry {
	FileName_t	 filename;
	FileAttributes_t	 fileAttributes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DirectoryEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DirectoryEntry;

#ifdef __cplusplus
}
#endif

#endif	/* _DirectoryEntry_H_ */
#include <asn_internal.h>
