/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EntryContent_H_
#define	_EntryContent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeOfDay.h"
#include "JOU-Additional-Detail.h"
#include <VisibleString.h>
#include "ObjectName.h"
#include "EC-State.h"
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include "Data.h"
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EntryContent__entryForm_PR {
	EntryContent__entryForm_PR_NOTHING,	/* No components present */
	EntryContent__entryForm_PR_data,
	EntryContent__entryForm_PR_annotation
} EntryContent__entryForm_PR;

/* EntryContent */
typedef struct EntryContent {
	TimeOfDay_t	 occurenceTime;
	JOU_Additional_Detail_t	*additionalDetail	/* OPTIONAL */;
	struct EntryContent__entryForm {
		EntryContent__entryForm_PR present;
		union EntryContent__entryForm_u {
			struct EntryContent__entryForm__data {
				struct EntryContent__entryForm__data__event {
					ObjectName_t	 eventConditionName;
					EC_State_t	 currentState;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *event;
				struct EntryContent__entryForm__data__listOfVariables {
					A_SEQUENCE_OF(struct EntryContent__entryForm__data__listOfVariables__Member {
						VisibleString_t	 variableTag;
						Data_t	 valueSpecification;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} ) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *listOfVariables;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} data;
			VisibleString_t	 annotation;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} entryForm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EntryContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntryContent;

#ifdef __cplusplus
}
#endif

#endif	/* _EntryContent_H_ */
#include <asn_internal.h>
