/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EntryContent.h"

static asn_TYPE_member_t asn_MBR_event_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EntryContent__entryForm__data__event, eventConditionName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventConditionName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntryContent__entryForm__data__event, currentState),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EC_State,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"currentState"
		},
};
static const ber_tlv_tag_t asn_DEF_event_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_event_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventConditionName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* currentState */
};
static asn_SEQUENCE_specifics_t asn_SPC_event_specs_6 = {
	sizeof(struct EntryContent__entryForm__data__event),
	offsetof(struct EntryContent__entryForm__data__event, _asn_ctx),
	asn_MAP_event_tag2el_6,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_event_6 = {
	"event",
	"event",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_event_tags_6,
	sizeof(asn_DEF_event_tags_6)
		/sizeof(asn_DEF_event_tags_6[0]) - 1, /* 1 */
	asn_DEF_event_tags_6,	/* Same as above */
	sizeof(asn_DEF_event_tags_6)
		/sizeof(asn_DEF_event_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_event_6,
	2,	/* Elements count */
	&asn_SPC_event_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EntryContent__entryForm__data__listOfVariables__Member, variableTag),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"variableTag"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntryContent__entryForm__data__listOfVariables__Member, valueSpecification),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Data,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"valueSpecification"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* variableTag */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* valueSpecification */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_10 = {
	sizeof(struct EntryContent__entryForm__data__listOfVariables__Member),
	offsetof(struct EntryContent__entryForm__data__listOfVariables__Member, _asn_ctx),
	asn_MAP_Member_tag2el_10,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_10 = {
	"SEQUENCE",
	"SEQUENCE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Member_tags_10,
	sizeof(asn_DEF_Member_tags_10)
		/sizeof(asn_DEF_Member_tags_10[0]), /* 1 */
	asn_DEF_Member_tags_10,	/* Same as above */
	sizeof(asn_DEF_Member_tags_10)
		/sizeof(asn_DEF_Member_tags_10[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Member_10,
	2,	/* Elements count */
	&asn_SPC_Member_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_listOfVariables_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listOfVariables_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfVariables_specs_9 = {
	sizeof(struct EntryContent__entryForm__data__listOfVariables),
	offsetof(struct EntryContent__entryForm__data__listOfVariables, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfVariables_9 = {
	"listOfVariables",
	"listOfVariables",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfVariables_tags_9,
	sizeof(asn_DEF_listOfVariables_tags_9)
		/sizeof(asn_DEF_listOfVariables_tags_9[0]) - 1, /* 1 */
	asn_DEF_listOfVariables_tags_9,	/* Same as above */
	sizeof(asn_DEF_listOfVariables_tags_9)
		/sizeof(asn_DEF_listOfVariables_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfVariables_9,
	1,	/* Single element */
	&asn_SPC_listOfVariables_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_data_5[] = {
	{ ATF_POINTER, 2, offsetof(struct EntryContent__entryForm__data, event),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_event_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"event"
		},
	{ ATF_POINTER, 1, offsetof(struct EntryContent__entryForm__data, listOfVariables),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listOfVariables_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfVariables"
		},
};
static const ber_tlv_tag_t asn_DEF_data_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_data_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* event */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* listOfVariables */
};
static asn_SEQUENCE_specifics_t asn_SPC_data_specs_5 = {
	sizeof(struct EntryContent__entryForm__data),
	offsetof(struct EntryContent__entryForm__data, _asn_ctx),
	asn_MAP_data_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_5 = {
	"data",
	"data",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_data_tags_5,
	sizeof(asn_DEF_data_tags_5)
		/sizeof(asn_DEF_data_tags_5[0]) - 1, /* 1 */
	asn_DEF_data_tags_5,	/* Same as above */
	sizeof(asn_DEF_data_tags_5)
		/sizeof(asn_DEF_data_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_data_5,
	2,	/* Elements count */
	&asn_SPC_data_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_entryForm_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EntryContent__entryForm, choice.data),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_data_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"data"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntryContent__entryForm, choice.annotation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"annotation"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_entryForm_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* data */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 } /* annotation */
};
static asn_CHOICE_specifics_t asn_SPC_entryForm_specs_4 = {
	sizeof(struct EntryContent__entryForm),
	offsetof(struct EntryContent__entryForm, _asn_ctx),
	offsetof(struct EntryContent__entryForm, present),
	sizeof(((struct EntryContent__entryForm *)0)->present),
	asn_MAP_entryForm_tag2el_4,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_entryForm_4 = {
	"entryForm",
	"entryForm",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_entryForm_4,
	2,	/* Elements count */
	&asn_SPC_entryForm_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_EntryContent_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EntryContent, occurenceTime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeOfDay,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occurenceTime"
		},
	{ ATF_POINTER, 1, offsetof(struct EntryContent, additionalDetail),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_JOU_Additional_Detail,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"additionalDetail"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EntryContent, entryForm),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_entryForm_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"entryForm"
		},
};
static const ber_tlv_tag_t asn_DEF_EntryContent_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EntryContent_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* occurenceTime */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* additionalDetail */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* data */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* annotation */
};
static asn_SEQUENCE_specifics_t asn_SPC_EntryContent_specs_1 = {
	sizeof(struct EntryContent),
	offsetof(struct EntryContent, _asn_ctx),
	asn_MAP_EntryContent_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_EntryContent = {
	"EntryContent",
	"EntryContent",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EntryContent_tags_1,
	sizeof(asn_DEF_EntryContent_tags_1)
		/sizeof(asn_DEF_EntryContent_tags_1[0]), /* 1 */
	asn_DEF_EntryContent_tags_1,	/* Same as above */
	sizeof(asn_DEF_EntryContent_tags_1)
		/sizeof(asn_DEF_EntryContent_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_EntryContent_1,
	3,	/* Elements count */
	&asn_SPC_EntryContent_specs_1	/* Additional specs */
};

