/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EventNotification_H_
#define	_EventNotification_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include "Unsigned8.h"
#include "EC-State.h"
#include "EventTime.h"
#include <BOOLEAN.h>
#include "AlarmAckRule.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include "ConfirmedServiceResponse.h"
#include "ServiceError.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EventNotification__eventConditionName_PR {
	EventNotification__eventConditionName_PR_NOTHING,	/* No components present */
	EventNotification__eventConditionName_PR_eventCondition,
	EventNotification__eventConditionName_PR_undefined
} EventNotification__eventConditionName_PR;
typedef enum EventNotification__actionResult__eventActionResult_PR {
	EventNotification__actionResult__eventActionResult_PR_NOTHING,	/* No components present */
	EventNotification__actionResult__eventActionResult_PR_success,
	EventNotification__actionResult__eventActionResult_PR_failure
} EventNotification__actionResult__eventActionResult_PR;

/* EventNotification */
typedef struct EventNotification {
	ObjectName_t	 eventEnrollmentName;
	struct EventNotification__eventConditionName {
		EventNotification__eventConditionName_PR present;
		union EventNotification__eventConditionName_u {
			ObjectName_t	 eventCondition;
			NULL_t	 undefined;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} eventConditionName;
	Unsigned8_t	 severity;
	EC_State_t	*currentState	/* OPTIONAL */;
	EventTime_t	 transitionTime;
	BOOLEAN_t	*notificationLost	/* DEFAULT FALSE */;
	AlarmAckRule_t	*alarmAcknowledgmentRule	/* OPTIONAL */;
	struct EventNotification__actionResult {
		ObjectName_t	 eventActioName;
		struct EventNotification__actionResult__eventActionResult {
			EventNotification__actionResult__eventActionResult_PR present;
			union EventNotification__actionResult__eventActionResult_u {
				ConfirmedServiceResponse_t	 success;
				ServiceError_t	 failure;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} eventActionResult;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *actionResult;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EventNotification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventNotification;

#ifdef __cplusplus
}
#endif

#endif	/* _EventNotification_H_ */
#include <asn_internal.h>
