/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EventNotification.h"

static asn_TYPE_member_t asn_MBR_eventConditionName_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventNotification__eventConditionName, choice.eventCondition),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventCondition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventNotification__eventConditionName, choice.undefined),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"undefined"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_eventConditionName_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventCondition */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* undefined */
};
static asn_CHOICE_specifics_t asn_SPC_eventConditionName_specs_3 = {
	sizeof(struct EventNotification__eventConditionName),
	offsetof(struct EventNotification__eventConditionName, _asn_ctx),
	offsetof(struct EventNotification__eventConditionName, present),
	sizeof(((struct EventNotification__eventConditionName *)0)->present),
	asn_MAP_eventConditionName_tag2el_3,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventConditionName_3 = {
	"eventConditionName",
	"eventConditionName",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_eventConditionName_3,
	2,	/* Elements count */
	&asn_SPC_eventConditionName_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventActionResult_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventNotification__actionResult__eventActionResult, choice.success),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ConfirmedServiceResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"success"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventNotification__actionResult__eventActionResult, choice.failure),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceError,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"failure"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_eventActionResult_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* success */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* failure */
};
static asn_CHOICE_specifics_t asn_SPC_eventActionResult_specs_13 = {
	sizeof(struct EventNotification__actionResult__eventActionResult),
	offsetof(struct EventNotification__actionResult__eventActionResult, _asn_ctx),
	offsetof(struct EventNotification__actionResult__eventActionResult, present),
	sizeof(((struct EventNotification__actionResult__eventActionResult *)0)->present),
	asn_MAP_eventActionResult_tag2el_13,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventActionResult_13 = {
	"eventActionResult",
	"eventActionResult",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_eventActionResult_13,
	2,	/* Elements count */
	&asn_SPC_eventActionResult_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_actionResult_11[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventNotification__actionResult, eventActioName),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventActioName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventNotification__actionResult, eventActionResult),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_eventActionResult_13,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventActionResult"
		},
};
static const ber_tlv_tag_t asn_DEF_actionResult_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_actionResult_tag2el_11[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 1 }, /* vmd-specific */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, -1, 0 }, /* success */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 1 }, /* domain-specific */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, -1, 0 }, /* failure */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 } /* aa-specific */
};
static asn_SEQUENCE_specifics_t asn_SPC_actionResult_specs_11 = {
	sizeof(struct EventNotification__actionResult),
	offsetof(struct EventNotification__actionResult, _asn_ctx),
	asn_MAP_actionResult_tag2el_11,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_actionResult_11 = {
	"actionResult",
	"actionResult",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_actionResult_tags_11,
	sizeof(asn_DEF_actionResult_tags_11)
		/sizeof(asn_DEF_actionResult_tags_11[0]) - 1, /* 1 */
	asn_DEF_actionResult_tags_11,	/* Same as above */
	sizeof(asn_DEF_actionResult_tags_11)
		/sizeof(asn_DEF_actionResult_tags_11[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_actionResult_11,
	2,	/* Elements count */
	&asn_SPC_actionResult_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_EventNotification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventNotification, eventEnrollmentName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventEnrollmentName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventNotification, eventConditionName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_eventConditionName_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventConditionName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventNotification, severity),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"severity"
		},
	{ ATF_POINTER, 1, offsetof(struct EventNotification, currentState),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EC_State,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"currentState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventNotification, transitionTime),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EventTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transitionTime"
		},
	{ ATF_POINTER, 3, offsetof(struct EventNotification, notificationLost),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"notificationLost"
		},
	{ ATF_POINTER, 2, offsetof(struct EventNotification, alarmAcknowledgmentRule),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlarmAckRule,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alarmAcknowledgmentRule"
		},
	{ ATF_POINTER, 1, offsetof(struct EventNotification, actionResult),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_actionResult_11,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"actionResult"
		},
};
static const ber_tlv_tag_t asn_DEF_EventNotification_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EventNotification_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventEnrollmentName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eventConditionName */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* severity */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* currentState */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* transitionTime */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* notificationLost */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* alarmAcknowledgmentRule */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 } /* actionResult */
};
static asn_SEQUENCE_specifics_t asn_SPC_EventNotification_specs_1 = {
	sizeof(struct EventNotification),
	offsetof(struct EventNotification, _asn_ctx),
	asn_MAP_EventNotification_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_EventNotification = {
	"EventNotification",
	"EventNotification",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EventNotification_tags_1,
	sizeof(asn_DEF_EventNotification_tags_1)
		/sizeof(asn_DEF_EventNotification_tags_1[0]), /* 1 */
	asn_DEF_EventNotification_tags_1,	/* Same as above */
	sizeof(asn_DEF_EventNotification_tags_1)
		/sizeof(asn_DEF_EventNotification_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_EventNotification_1,
	8,	/* Elements count */
	&asn_SPC_EventNotification_specs_1	/* Additional specs */
};

