/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EventEnrollment.h"

static asn_TYPE_member_t asn_MBR_eventConditionName_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventEnrollment__eventConditionName, choice.eventCondition),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventCondition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventEnrollment__eventConditionName, choice.undefined),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"undefined"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_eventConditionName_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventCondition */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* undefined */
};
static asn_CHOICE_specifics_t asn_SPC_eventConditionName_specs_3 = {
	sizeof(struct EventEnrollment__eventConditionName),
	offsetof(struct EventEnrollment__eventConditionName, _asn_ctx),
	offsetof(struct EventEnrollment__eventConditionName, present),
	sizeof(((struct EventEnrollment__eventConditionName *)0)->present),
	asn_MAP_eventConditionName_tag2el_3,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventConditionName_3 = {
	"eventConditionName",
	"eventConditionName",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_eventConditionName_3,
	2,	/* Elements count */
	&asn_SPC_eventConditionName_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventActionName_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventEnrollment__eventActionName, choice.eventAction),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventAction"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventEnrollment__eventActionName, choice.undefined),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"undefined"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_eventActionName_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventAction */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* undefined */
};
static asn_CHOICE_specifics_t asn_SPC_eventActionName_specs_6 = {
	sizeof(struct EventEnrollment__eventActionName),
	offsetof(struct EventEnrollment__eventActionName, _asn_ctx),
	offsetof(struct EventEnrollment__eventActionName, present),
	sizeof(((struct EventEnrollment__eventActionName *)0)->present),
	asn_MAP_eventActionName_tag2el_6,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventActionName_6 = {
	"eventActionName",
	"eventActionName",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_eventActionName_6,
	2,	/* Elements count */
	&asn_SPC_eventActionName_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_EventEnrollment_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventEnrollment, eventEnrollmentName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventEnrollmentName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventEnrollment, eventConditionName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_eventConditionName_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventConditionName"
		},
	{ ATF_POINTER, 2, offsetof(struct EventEnrollment, eventActionName),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_eventActionName_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventActionName"
		},
	{ ATF_POINTER, 1, offsetof(struct EventEnrollment, mmsDeletable),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mmsDeletable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventEnrollment, enrollmentClass),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EE_Class,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enrollmentClass"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventEnrollment, duration),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EE_Duration,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"duration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventEnrollment, invokeID),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"invokeID"
		},
	{ ATF_POINTER, 1, offsetof(struct EventEnrollment, remainingAcceptableDelay),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"remainingAcceptableDelay"
		},
};
static const ber_tlv_tag_t asn_DEF_EventEnrollment_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EventEnrollment_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventEnrollmentName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eventConditionName */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* eventActionName */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* mmsDeletable */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* enrollmentClass */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* duration */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* invokeID */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 } /* remainingAcceptableDelay */
};
static asn_SEQUENCE_specifics_t asn_SPC_EventEnrollment_specs_1 = {
	sizeof(struct EventEnrollment),
	offsetof(struct EventEnrollment, _asn_ctx),
	asn_MAP_EventEnrollment_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_EventEnrollment = {
	"EventEnrollment",
	"EventEnrollment",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EventEnrollment_tags_1,
	sizeof(asn_DEF_EventEnrollment_tags_1)
		/sizeof(asn_DEF_EventEnrollment_tags_1[0]), /* 1 */
	asn_DEF_EventEnrollment_tags_1,	/* Same as above */
	sizeof(asn_DEF_EventEnrollment_tags_1)
		/sizeof(asn_DEF_EventEnrollment_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_EventEnrollment_1,
	8,	/* Elements count */
	&asn_SPC_EventEnrollment_specs_1	/* Additional specs */
};

