/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EventEnrollment_H_
#define	_EventEnrollment_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include <BOOLEAN.h>
#include "EE-Class.h"
#include "EE-Duration.h"
#include "Unsigned32.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EventEnrollment__eventConditionName_PR {
	EventEnrollment__eventConditionName_PR_NOTHING,	/* No components present */
	EventEnrollment__eventConditionName_PR_eventCondition,
	EventEnrollment__eventConditionName_PR_undefined
} EventEnrollment__eventConditionName_PR;
typedef enum EventEnrollment__eventActionName_PR {
	EventEnrollment__eventActionName_PR_NOTHING,	/* No components present */
	EventEnrollment__eventActionName_PR_eventAction,
	EventEnrollment__eventActionName_PR_undefined
} EventEnrollment__eventActionName_PR;

/* EventEnrollment */
typedef struct EventEnrollment {
	ObjectName_t	 eventEnrollmentName;
	struct EventEnrollment__eventConditionName {
		EventEnrollment__eventConditionName_PR present;
		union EventEnrollment__eventConditionName_u {
			ObjectName_t	 eventCondition;
			NULL_t	 undefined;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} eventConditionName;
	struct EventEnrollment__eventActionName {
		EventEnrollment__eventActionName_PR present;
		union EventEnrollment__eventActionName_u {
			ObjectName_t	 eventAction;
			NULL_t	 undefined;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *eventActionName;
	BOOLEAN_t	*mmsDeletable	/* DEFAULT FALSE */;
	EE_Class_t	 enrollmentClass;
	EE_Duration_t	 duration;
	Unsigned32_t	 invokeID;
	Unsigned32_t	*remainingAcceptableDelay	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EventEnrollment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventEnrollment;

#ifdef __cplusplus
}
#endif

#endif	/* _EventEnrollment_H_ */
#include <asn_internal.h>
