/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_FileAttributes_H_
#define	_FileAttributes_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include <GeneralizedTime.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FileAttributes */
typedef struct FileAttributes {
	Unsigned32_t	 sizeOfFile;
	GeneralizedTime_t	*lastModified	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileAttributes;

#ifdef __cplusplus
}
#endif

#endif	/* _FileAttributes_H_ */
#include <asn_internal.h>
