/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_FileOpen_Request_H_
#define	_FileOpen_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FileName.h"
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FileOpen-Request */
typedef struct FileOpen_Request {
	FileName_t	 fileName;
	Unsigned32_t	 initialPosition;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileOpen_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileOpen_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _FileOpen_Request_H_ */
#include <asn_internal.h>
