/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_FileName_H_
#define	_FileName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GraphicString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FileName */
typedef struct FileName {
	A_SEQUENCE_OF(GraphicString_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileName;

#ifdef __cplusplus
}
#endif

#endif	/* _FileName_H_ */
#include <asn_internal.h>
