/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_FileDirectory_Request_H_
#define	_FileDirectory_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FileName;

/* FileDirectory-Request */
typedef struct FileDirectory_Request {
	struct FileName	*fileSpecification	/* OPTIONAL */;
	struct FileName	*continueAfter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileDirectory_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileDirectory_Request;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FileName.h"

#endif	/* _FileDirectory_Request_H_ */
#include <asn_internal.h>
