/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "GetAlarmSummary-Request.h"

static int asn_DFL_4_set_0(int set_value, void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 0 */
		*st = 0;
		return 0;
	} else {
		/* Test default value 0 */
		return (*st == 0);
	}
}
static asn_TYPE_member_t asn_MBR_severityFilter_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetAlarmSummary_Request__severityFilter, mostSevere),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mostSevere"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetAlarmSummary_Request__severityFilter, leastSevere),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"leastSevere"
		},
};
static const ber_tlv_tag_t asn_DEF_severityFilter_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_severityFilter_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mostSevere */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* leastSevere */
};
static asn_SEQUENCE_specifics_t asn_SPC_severityFilter_specs_8 = {
	sizeof(struct GetAlarmSummary_Request__severityFilter),
	offsetof(struct GetAlarmSummary_Request__severityFilter, _asn_ctx),
	asn_MAP_severityFilter_tag2el_8,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_severityFilter_8 = {
	"severityFilter",
	"severityFilter",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_severityFilter_tags_8,
	sizeof(asn_DEF_severityFilter_tags_8)
		/sizeof(asn_DEF_severityFilter_tags_8[0]) - 1, /* 1 */
	asn_DEF_severityFilter_tags_8,	/* Same as above */
	sizeof(asn_DEF_severityFilter_tags_8)
		/sizeof(asn_DEF_severityFilter_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_severityFilter_8,
	2,	/* Elements count */
	&asn_SPC_severityFilter_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_GetAlarmSummary_Request_1[] = {
	{ ATF_POINTER, 5, offsetof(struct GetAlarmSummary_Request, enrollmentsOnly),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enrollmentsOnly"
		},
	{ ATF_POINTER, 4, offsetof(struct GetAlarmSummary_Request, activeAlarmsOnly),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"activeAlarmsOnly"
		},
	{ ATF_NOFLAGS, 3, offsetof(struct GetAlarmSummary_Request, acknowledgmentFilter),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_4_set_0,	/* DEFAULT 0 */
		"acknowledgmentFilter"
		},
	{ ATF_POINTER, 2, offsetof(struct GetAlarmSummary_Request, severityFilter),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_severityFilter_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"severityFilter"
		},
	{ ATF_POINTER, 1, offsetof(struct GetAlarmSummary_Request, continueAfter),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"continueAfter"
		},
};
static const ber_tlv_tag_t asn_DEF_GetAlarmSummary_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetAlarmSummary_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* enrollmentsOnly */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* activeAlarmsOnly */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* acknowledgmentFilter */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* severityFilter */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 } /* continueAfter */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetAlarmSummary_Request_specs_1 = {
	sizeof(struct GetAlarmSummary_Request),
	offsetof(struct GetAlarmSummary_Request, _asn_ctx),
	asn_MAP_GetAlarmSummary_Request_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GetAlarmSummary_Request = {
	"GetAlarmSummary-Request",
	"GetAlarmSummary-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GetAlarmSummary_Request_tags_1,
	sizeof(asn_DEF_GetAlarmSummary_Request_tags_1)
		/sizeof(asn_DEF_GetAlarmSummary_Request_tags_1[0]), /* 1 */
	asn_DEF_GetAlarmSummary_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetAlarmSummary_Request_tags_1)
		/sizeof(asn_DEF_GetAlarmSummary_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GetAlarmSummary_Request_1,
	5,	/* Elements count */
	&asn_SPC_GetAlarmSummary_Request_specs_1	/* Additional specs */
};

