/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetAlarmEnrollmentSummary_Request_H_
#define	_GetAlarmEnrollmentSummary_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include "Unsigned8.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetAlarmEnrollmentSummary_Request__acknowledgmentFilter {
	GetAlarmEnrollmentSummary_Request__acknowledgmentFilter_not_acked	= 0,
	GetAlarmEnrollmentSummary_Request__acknowledgmentFilter_acked	= 1,
	GetAlarmEnrollmentSummary_Request__acknowledgmentFilter_all	= 2
} e_GetAlarmEnrollmentSummary_Request__acknowledgmentFilter;

/* Forward declarations */
struct ObjectName;

/* GetAlarmEnrollmentSummary-Request */
typedef struct GetAlarmEnrollmentSummary_Request {
	BOOLEAN_t	*enrollmentsOnly	/* DEFAULT TRUE */;
	BOOLEAN_t	*activeAlarmsOnly	/* DEFAULT TRUE */;
	long	 acknowledgmentFilter	/* DEFAULT 0 */;
	struct GetAlarmEnrollmentSummary_Request__severityFilter {
		Unsigned8_t	 mostSevere;
		Unsigned8_t	 leastSevere;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *severityFilter;
	struct ObjectName	*continueAfter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetAlarmEnrollmentSummary_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetAlarmEnrollmentSummary_Request;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _GetAlarmEnrollmentSummary_Request_H_ */
#include <asn_internal.h>
