/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetCapabilityList_Request_H_
#define	_GetCapabilityList_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetCapabilityList-Request */
typedef struct GetCapabilityList_Request {
	VisibleString_t	*continueAfter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetCapabilityList_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetCapabilityList_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _GetCapabilityList_Request_H_ */
#include <asn_internal.h>
