/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetCapabilityList_Response_H_
#define	_GetCapabilityList_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <VisibleString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetCapabilityList-Response */
typedef struct GetCapabilityList_Response {
	struct GetCapabilityList_Response__listOfCapabilities {
		A_SEQUENCE_OF(VisibleString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfCapabilities;
	BOOLEAN_t	*moreFollows	/* DEFAULT TRUE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetCapabilityList_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetCapabilityList_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _GetCapabilityList_Response_H_ */
#include <asn_internal.h>
