/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetDomainAttributes_Response_H_
#define	_GetDomainAttributes_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DomainState.h"
#include <BOOLEAN.h>
#include "Integer8.h"
#include <VisibleString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "Identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetDomainAttributes-Response */
typedef struct GetDomainAttributes_Response {
	struct GetDomainAttributes_Response__listOfCapabilities {
		A_SEQUENCE_OF(VisibleString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfCapabilities;
	DomainState_t	 state;
	BOOLEAN_t	 mmsDeletable;
	BOOLEAN_t	 sharable;
	struct GetDomainAttributes_Response__listOfProgramInvocations {
		A_SEQUENCE_OF(Identifier_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfProgramInvocations;
	Integer8_t	 uploadInProgress;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetDomainAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetDomainAttributes_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _GetDomainAttributes_Response_H_ */
#include <asn_internal.h>
