/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "GetEventEnrollmentAttributes-Request.h"

static int asn_DFL_2_set_1(int set_value, void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 1 */
		*st = 1;
		return 0;
	} else {
		/* Test default value 1 */
		return (*st == 1);
	}
}
static asn_TYPE_member_t asn_MBR_eventEnrollmentNames_7[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_eventEnrollmentNames_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_eventEnrollmentNames_specs_7 = {
	sizeof(struct GetEventEnrollmentAttributes_Request__eventEnrollmentNames),
	offsetof(struct GetEventEnrollmentAttributes_Request__eventEnrollmentNames, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventEnrollmentNames_7 = {
	"eventEnrollmentNames",
	"eventEnrollmentNames",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventEnrollmentNames_tags_7,
	sizeof(asn_DEF_eventEnrollmentNames_tags_7)
		/sizeof(asn_DEF_eventEnrollmentNames_tags_7[0]) - 1, /* 1 */
	asn_DEF_eventEnrollmentNames_tags_7,	/* Same as above */
	sizeof(asn_DEF_eventEnrollmentNames_tags_7)
		/sizeof(asn_DEF_eventEnrollmentNames_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventEnrollmentNames_7,
	1,	/* Single element */
	&asn_SPC_eventEnrollmentNames_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_GetEventEnrollmentAttributes_Request_1[] = {
	{ ATF_POINTER, 5, offsetof(struct GetEventEnrollmentAttributes_Request, scopeOfRequest),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_2_set_1,	/* DEFAULT 1 */
		"scopeOfRequest"
		},
	{ ATF_POINTER, 4, offsetof(struct GetEventEnrollmentAttributes_Request, eventEnrollmentNames),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_eventEnrollmentNames_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventEnrollmentNames"
		},
	{ ATF_POINTER, 3, offsetof(struct GetEventEnrollmentAttributes_Request, eventConditionName),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventConditionName"
		},
	{ ATF_POINTER, 2, offsetof(struct GetEventEnrollmentAttributes_Request, eventActionName),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"eventActionName"
		},
	{ ATF_POINTER, 1, offsetof(struct GetEventEnrollmentAttributes_Request, continueAfter),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"continueAfter"
		},
};
static const ber_tlv_tag_t asn_DEF_GetEventEnrollmentAttributes_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetEventEnrollmentAttributes_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* scopeOfRequest */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eventEnrollmentNames */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* eventConditionName */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* eventActionName */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 } /* continueAfter */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetEventEnrollmentAttributes_Request_specs_1 = {
	sizeof(struct GetEventEnrollmentAttributes_Request),
	offsetof(struct GetEventEnrollmentAttributes_Request, _asn_ctx),
	asn_MAP_GetEventEnrollmentAttributes_Request_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GetEventEnrollmentAttributes_Request = {
	"GetEventEnrollmentAttributes-Request",
	"GetEventEnrollmentAttributes-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GetEventEnrollmentAttributes_Request_tags_1,
	sizeof(asn_DEF_GetEventEnrollmentAttributes_Request_tags_1)
		/sizeof(asn_DEF_GetEventEnrollmentAttributes_Request_tags_1[0]), /* 1 */
	asn_DEF_GetEventEnrollmentAttributes_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetEventEnrollmentAttributes_Request_tags_1)
		/sizeof(asn_DEF_GetEventEnrollmentAttributes_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GetEventEnrollmentAttributes_Request_1,
	5,	/* Elements count */
	&asn_SPC_GetEventEnrollmentAttributes_Request_specs_1	/* Additional specs */
};

