/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetEventActionAttributes_Response_H_
#define	_GetEventActionAttributes_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Modifier;

/* GetEventActionAttributes-Response */
typedef struct GetEventActionAttributes_Response {
	BOOLEAN_t	*mmsDeletable	/* DEFAULT FALSE */;
	struct GetEventActionAttributes_Response__listOfModifier {
		A_SEQUENCE_OF(struct Modifier) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfModifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetEventActionAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetEventActionAttributes_Response;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Modifier.h"

#endif	/* _GetEventActionAttributes_Response_H_ */
#include <asn_internal.h>
