/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "GetNameList-Request.h"

static asn_TYPE_member_t asn_MBR_extendedObjectClass_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetNameList_Request__extendedObjectClass, choice.objectClass),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObjectClass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"objectClass"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_extendedObjectClass_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* objectClass */
};
static asn_CHOICE_specifics_t asn_SPC_extendedObjectClass_specs_2 = {
	sizeof(struct GetNameList_Request__extendedObjectClass),
	offsetof(struct GetNameList_Request__extendedObjectClass, _asn_ctx),
	offsetof(struct GetNameList_Request__extendedObjectClass, present),
	sizeof(((struct GetNameList_Request__extendedObjectClass *)0)->present),
	asn_MAP_extendedObjectClass_tag2el_2,
	1,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_extendedObjectClass_2 = {
	"extendedObjectClass",
	"extendedObjectClass",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_extendedObjectClass_2,
	1,	/* Elements count */
	&asn_SPC_extendedObjectClass_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_GetNameList_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetNameList_Request, extendedObjectClass),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_extendedObjectClass_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extendedObjectClass"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetNameList_Request, objectScope),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectScope,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"objectScope"
		},
	{ ATF_POINTER, 1, offsetof(struct GetNameList_Request, continueAfter),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"continueAfter"
		},
};
static const ber_tlv_tag_t asn_DEF_GetNameList_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetNameList_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* extendedObjectClass */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* objectScope */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* continueAfter */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetNameList_Request_specs_1 = {
	sizeof(struct GetNameList_Request),
	offsetof(struct GetNameList_Request, _asn_ctx),
	asn_MAP_GetNameList_Request_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GetNameList_Request = {
	"GetNameList-Request",
	"GetNameList-Request",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GetNameList_Request_tags_1,
	sizeof(asn_DEF_GetNameList_Request_tags_1)
		/sizeof(asn_DEF_GetNameList_Request_tags_1[0]), /* 1 */
	asn_DEF_GetNameList_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetNameList_Request_tags_1)
		/sizeof(asn_DEF_GetNameList_Request_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GetNameList_Request_1,
	3,	/* Elements count */
	&asn_SPC_GetNameList_Request_specs_1	/* Additional specs */
};

