/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetNamedVariableListAttributes_Response_H_
#define	_GetNamedVariableListAttributes_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "VariableSpecification.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlternateAccess;

/* GetNamedVariableListAttributes-Response */
typedef struct GetNamedVariableListAttributes_Response {
	BOOLEAN_t	 mmsDeletable;
	struct GetNamedVariableListAttributes_Response__listOfVariable {
		A_SEQUENCE_OF(struct GetNamedVariableListAttributes_Response__listOfVariable__Member {
			VariableSpecification_t	 variableSpecification;
			struct AlternateAccess	*alternateAccess	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfVariable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetNamedVariableListAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetNamedVariableListAttributes_Response;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlternateAccess.h"

#endif	/* _GetNamedVariableListAttributes_Response_H_ */
#include <asn_internal.h>
