/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetNameList_Request_H_
#define	_GetNameList_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectScope.h"
#include "Identifier.h"
#include "ObjectClass.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetNameList_Request__extendedObjectClass_PR {
	GetNameList_Request__extendedObjectClass_PR_NOTHING,	/* No components present */
	GetNameList_Request__extendedObjectClass_PR_objectClass
} GetNameList_Request__extendedObjectClass_PR;

/* GetNameList-Request */
typedef struct GetNameList_Request {
	struct GetNameList_Request__extendedObjectClass {
		GetNameList_Request__extendedObjectClass_PR present;
		union GetNameList_Request__extendedObjectClass_u {
			ObjectClass_t	 objectClass;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extendedObjectClass;
	ObjectScope_t	 objectScope;
	Identifier_t	*continueAfter	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetNameList_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetNameList_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _GetNameList_Request_H_ */
#include <asn_internal.h>
