/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetScatteredAccessAttributes_Response_H_
#define	_GetScatteredAccessAttributes_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "ScatteredAccessDescription.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetScatteredAccessAttributes-Response */
typedef struct GetScatteredAccessAttributes_Response {
	BOOLEAN_t	 mmsDeletable;
	ScatteredAccessDescription_t	 scatteredAccessDescription;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetScatteredAccessAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetScatteredAccessAttributes_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _GetScatteredAccessAttributes_Response_H_ */
#include <asn_internal.h>
