/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetVariableAccessAttributes_Response_H_
#define	_GetVariableAccessAttributes_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "TypeSpecification.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Address;

/* GetVariableAccessAttributes-Response */
typedef struct GetVariableAccessAttributes_Response {
	BOOLEAN_t	 mmsDeletable;
	struct Address	*address	/* OPTIONAL */;
	TypeSpecification_t	 typeSpecification;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetVariableAccessAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetVariableAccessAttributes_Response;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Address.h"

#endif	/* _GetVariableAccessAttributes_Response_H_ */
#include <asn_internal.h>
