/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../../../../utils/mms-simple.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GetVariableAccessAttributesRequest_H_
#define	_GetVariableAccessAttributesRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetVariableAccessAttributesRequest_PR {
	GetVariableAccessAttributesRequest_PR_NOTHING,	/* No components present */
	GetVariableAccessAttributesRequest_PR_name
} GetVariableAccessAttributesRequest_PR;

/* GetVariableAccessAttributesRequest */
typedef struct GetVariableAccessAttributesRequest {
	GetVariableAccessAttributesRequest_PR present;
	union GetVariableAccessAttributesRequest_u {
		ObjectName_t	 name;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetVariableAccessAttributesRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetVariableAccessAttributesRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _GetVariableAccessAttributesRequest_H_ */
#include <asn_internal.h>
