/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Identify_Request_H_
#define	_Identify_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Identify-Request */
typedef NULL_t	 Identify_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Identify_Request;
asn_struct_free_f Identify_Request_free;
asn_struct_print_f Identify_Request_print;
asn_constr_check_f Identify_Request_constraint;
ber_type_decoder_f Identify_Request_decode_ber;
der_type_encoder_f Identify_Request_encode_der;
xer_type_decoder_f Identify_Request_decode_xer;
xer_type_encoder_f Identify_Request_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Identify_Request_H_ */
#include <asn_internal.h>
