/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Identify_Response_H_
#define	_Identify_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <OBJECT_IDENTIFIER.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Identify-Response */
typedef struct Identify_Response {
	VisibleString_t	 vendorName;
	VisibleString_t	 modelName;
	VisibleString_t	 revision;
	struct Identify_Response__listOfAbstractSyntaxes {
		A_SEQUENCE_OF(OBJECT_IDENTIFIER_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfAbstractSyntaxes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Identify_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Identify_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _Identify_Response_H_ */
#include <asn_internal.h>
