/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_InformationReport_H_
#define	_InformationReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VariableAccessSpecification.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AccessResult;

/* InformationReport */
typedef struct InformationReport {
	VariableAccessSpecification_t	 variableAccessSpecification;
	struct InformationReport__listOfAccessResult {
		A_SEQUENCE_OF(struct AccessResult) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfAccessResult;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InformationReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InformationReport;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AccessResult.h"

#endif	/* _InformationReport_H_ */
#include <asn_internal.h>
