/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Initiate_RequestPDU_H_
#define	_Initiate_RequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Integer32.h"
#include "Integer16.h"
#include "Integer8.h"
#include "InitRequestDetail.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Initiate-RequestPDU */
typedef struct Initiate_RequestPDU {
	Integer32_t	*localDetailCalling	/* OPTIONAL */;
	Integer16_t	 proposedMaxServOutstandingCalling;
	Integer16_t	 proposedMaxServOutstandingCalled;
	Integer8_t	*proposedDataStructureNestingLevel	/* OPTIONAL */;
	InitRequestDetail_t	 mmsInitRequestDetail;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Initiate_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Initiate_RequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _Initiate_RequestPDU_H_ */
#include <asn_internal.h>
