/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_InitiateUnitControl_Error_H_
#define	_InitiateUnitControl_Error_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InitiateUnitControl_Error_PR {
	InitiateUnitControl_Error_PR_NOTHING,	/* No components present */
	InitiateUnitControl_Error_PR_domain,
	InitiateUnitControl_Error_PR_programInvocation
} InitiateUnitControl_Error_PR;

/* InitiateUnitControl-Error */
typedef struct InitiateUnitControl_Error {
	InitiateUnitControl_Error_PR present;
	union InitiateUnitControl_Error_u {
		Identifier_t	 domain;
		Identifier_t	 programInvocation;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiateUnitControl_Error_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiateUnitControl_Error;

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateUnitControl_Error_H_ */
#include <asn_internal.h>
