/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_InitiateDownloadSequence_Request_H_
#define	_InitiateDownloadSequence_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <BOOLEAN.h>
#include <VisibleString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitiateDownloadSequence-Request */
typedef struct InitiateDownloadSequence_Request {
	Identifier_t	 domainName;
	struct InitiateDownloadSequence_Request__listOfCapabilities {
		A_SEQUENCE_OF(VisibleString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfCapabilities;
	BOOLEAN_t	 sharable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiateDownloadSequence_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiateDownloadSequence_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateDownloadSequence_Request_H_ */
#include <asn_internal.h>
