/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Initiate_ResponsePDU_H_
#define	_Initiate_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Integer32.h"
#include "Integer16.h"
#include "Integer8.h"
#include "InitResponseDetail.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Initiate-ResponsePDU */
typedef struct Initiate_ResponsePDU {
	Integer32_t	*localDetailCalled	/* OPTIONAL */;
	Integer16_t	 negociatedMaxServOutstandingCalling;
	Integer16_t	 negociatedMaxServOutstandingCalled;
	Integer8_t	*negociatedDataStructureNestingLevel	/* OPTIONAL */;
	InitResponseDetail_t	 mmsInitResponseDetail;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Initiate_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Initiate_ResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _Initiate_ResponsePDU_H_ */
#include <asn_internal.h>
