/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Input_Request_H_
#define	_Input_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <BOOLEAN.h>
#include "Unsigned32.h"
#include <VisibleString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Input-Request */
typedef struct Input_Request {
	Identifier_t	 operatorStationName;
	BOOLEAN_t	*echo	/* DEFAULT TRUE */;
	struct Input_Request__listOfPromptData {
		A_SEQUENCE_OF(VisibleString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfPromptData;
	Unsigned32_t	*inputTimeOut	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Input_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Input_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _Input_Request_H_ */
#include <asn_internal.h>
