/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_JOU_Additional_Detail_H_
#define	_JOU_Additional_Detail_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* JOU-Additional-Detail */
typedef NULL_t	 JOU_Additional_Detail_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_JOU_Additional_Detail;
asn_struct_free_f JOU_Additional_Detail_free;
asn_struct_print_f JOU_Additional_Detail_print;
asn_constr_check_f JOU_Additional_Detail_constraint;
ber_type_decoder_f JOU_Additional_Detail_decode_ber;
der_type_encoder_f JOU_Additional_Detail_encode_der;
xer_type_decoder_f JOU_Additional_Detail_decode_xer;
xer_type_encoder_f JOU_Additional_Detail_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _JOU_Additional_Detail_H_ */
#include <asn_internal.h>
