/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Kill_Request_H_
#define	_Kill_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Kill-Request */
typedef struct Kill_Request {
	Identifier_t	 programInvocationName;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Kill_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Kill_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _Kill_Request_H_ */
#include <asn_internal.h>
