/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LoadUnitControlFromFile_Error_H_
#define	_LoadUnitControlFromFile_Error_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "Identifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoadUnitControlFromFile_Error_PR {
	LoadUnitControlFromFile_Error_PR_NOTHING,	/* No components present */
	LoadUnitControlFromFile_Error_PR_none,
	LoadUnitControlFromFile_Error_PR_domain,
	LoadUnitControlFromFile_Error_PR_programInvocation
} LoadUnitControlFromFile_Error_PR;

/* LoadUnitControlFromFile-Error */
typedef struct LoadUnitControlFromFile_Error {
	LoadUnitControlFromFile_Error_PR present;
	union LoadUnitControlFromFile_Error_u {
		NULL_t	 none;
		Identifier_t	 domain;
		Identifier_t	 programInvocation;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoadUnitControlFromFile_Error_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadUnitControlFromFile_Error;

#ifdef __cplusplus
}
#endif

#endif	/* _LoadUnitControlFromFile_Error_H_ */
#include <asn_internal.h>
