/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "MMSpdu.h"

static asn_TYPE_member_t asn_MBR_MMSpdu_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.confirmed_RequestPDU),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Confirmed_RequestPDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"confirmed-RequestPDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.confirmed_ResponsePDU),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Confirmed_ResponsePDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"confirmed-ResponsePDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.confirmed_ErrorPDU),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Confirmed_ErrorPDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"confirmed-ErrorPDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.unconfirmed_PDU),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unconfirmed_PDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unconfirmed-PDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.rejectPDU),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RejectPDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rejectPDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.cancel_RequestPDU),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Cancel_RequestPDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cancel-RequestPDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.cancel_ResponsePDU),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Cancel_ResponsePDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cancel-ResponsePDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.cancel_ErrorPDU),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Cancel_ErrorPDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cancel-ErrorPDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.initiate_RequestPDU),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Initiate_RequestPDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"initiate-RequestPDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.initiate_ResponsePDU),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Initiate_ResponsePDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"initiate-ResponsePDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.initiate_ErrorPDU),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Initiate_ErrorPDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"initiate-ErrorPDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.conclude_RequestPDU),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Conclude_RequestPDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"conclude-RequestPDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.conclude_ResponsePDU),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Conclude_ResponsePDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"conclude-ResponsePDU"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MMSpdu, choice.conclude_ErrorPDU),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Conclude_ErrorPDU,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"conclude-ErrorPDU"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MMSpdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* confirmed-RequestPDU */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* confirmed-ResponsePDU */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* confirmed-ErrorPDU */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* unconfirmed-PDU */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* rejectPDU */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* cancel-RequestPDU */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* cancel-ResponsePDU */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* cancel-ErrorPDU */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* initiate-RequestPDU */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* initiate-ResponsePDU */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* initiate-ErrorPDU */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* conclude-RequestPDU */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* conclude-ResponsePDU */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 } /* conclude-ErrorPDU */
};
static asn_CHOICE_specifics_t asn_SPC_MMSpdu_specs_1 = {
	sizeof(struct MMSpdu),
	offsetof(struct MMSpdu, _asn_ctx),
	offsetof(struct MMSpdu, present),
	sizeof(((struct MMSpdu *)0)->present),
	asn_MAP_MMSpdu_tag2el_1,
	14,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MMSpdu = {
	"MMSpdu",
	"MMSpdu",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_MMSpdu_1,
	14,	/* Elements count */
	&asn_SPC_MMSpdu_specs_1	/* Additional specs */
};

