/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Modifier_H_
#define	_Modifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttachToEventCondition.h"
#include "AttachToSemaphore.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Modifier_PR {
	Modifier_PR_NOTHING,	/* No components present */
	Modifier_PR_attach_To_Event_Condition,
	Modifier_PR_attach_To_Semaphore
} Modifier_PR;

/* Modifier */
typedef struct Modifier {
	Modifier_PR present;
	union Modifier_u {
		AttachToEventCondition_t	 attach_To_Event_Condition;
		AttachToSemaphore_t	 attach_To_Semaphore;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Modifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Modifier;

#ifdef __cplusplus
}
#endif

#endif	/* _Modifier_H_ */
#include <asn_internal.h>
