/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ObjectClass_H_
#define	_ObjectClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ObjectClass {
	ObjectClass_nammedVariable	= 0,
	ObjectClass_scatteredAccess	= 1,
	ObjectClass_namedVariableList	= 2,
	ObjectClass_namedType	= 3,
	ObjectClass_semaphore	= 4,
	ObjectClass_eventCondition	= 5,
	ObjectClass_eventAction	= 6,
	ObjectClass_eventEnrollment	= 7,
	ObjectClass_journal	= 8,
	ObjectClass_domain	= 9,
	ObjectClass_programInvocation	= 10,
	ObjectClass_operatorStation	= 11
} e_ObjectClass;

/* ObjectClass */
typedef long	 ObjectClass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectClass;
asn_struct_free_f ObjectClass_free;
asn_struct_print_f ObjectClass_print;
asn_constr_check_f ObjectClass_constraint;
ber_type_decoder_f ObjectClass_decode_ber;
der_type_encoder_f ObjectClass_encode_der;
xer_type_decoder_f ObjectClass_decode_xer;
xer_type_encoder_f ObjectClass_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectClass_H_ */
#include <asn_internal.h>
