/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ObjectScope_H_
#define	_ObjectScope_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "Identifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ObjectScope_PR {
	ObjectScope_PR_NOTHING,	/* No components present */
	ObjectScope_PR_vmdSpecific,
	ObjectScope_PR_domainSpecific,
	ObjectScope_PR_aaSpecific
} ObjectScope_PR;

/* ObjectScope */
typedef struct ObjectScope {
	ObjectScope_PR present;
	union ObjectScope_u {
		NULL_t	 vmdSpecific;
		Identifier_t	 domainSpecific;
		NULL_t	 aaSpecific;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ObjectScope_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectScope;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectScope_H_ */
#include <asn_internal.h>
