/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ObjectScope.h"

static asn_TYPE_member_t asn_MBR_ObjectScope_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectScope, choice.vmdSpecific),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vmdSpecific"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectScope, choice.domainSpecific),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"domainSpecific"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectScope, choice.aaSpecific),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"aaSpecific"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ObjectScope_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vmdSpecific */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* domainSpecific */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* aaSpecific */
};
static asn_CHOICE_specifics_t asn_SPC_ObjectScope_specs_1 = {
	sizeof(struct ObjectScope),
	offsetof(struct ObjectScope, _asn_ctx),
	offsetof(struct ObjectScope, present),
	sizeof(((struct ObjectScope *)0)->present),
	asn_MAP_ObjectScope_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ObjectScope = {
	"ObjectScope",
	"ObjectScope",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ObjectScope_1,
	3,	/* Elements count */
	&asn_SPC_ObjectScope_specs_1	/* Additional specs */
};

