/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ReadJournal_Response_H_
#define	_ReadJournal_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct JournalEntry;

/* ReadJournal-Response */
typedef struct ReadJournal_Response {
	struct ReadJournal_Response__listOfJournalEntry {
		A_SEQUENCE_OF(struct JournalEntry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfJournalEntry;
	BOOLEAN_t	*moreFollows	/* DEFAULT FALSE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReadJournal_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReadJournal_Response;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "JournalEntry.h"

#endif	/* _ReadJournal_Response_H_ */
#include <asn_internal.h>
