/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Rename_Request_H_
#define	_Rename_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include "Identifier.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Rename_Request__extendedObjectClass_PR {
	Rename_Request__extendedObjectClass_PR_NOTHING,	/* No components present */
	Rename_Request__extendedObjectClass_PR_objectClass
} Rename_Request__extendedObjectClass_PR;
typedef enum Rename_Request__extendedObjectClass__objectClass {
	Rename_Request__extendedObjectClass__objectClass_namedVariable	= 0,
	Rename_Request__extendedObjectClass__objectClass_scatteredAccess	= 1,
	Rename_Request__extendedObjectClass__objectClass_namedVariableList	= 2,
	Rename_Request__extendedObjectClass__objectClass_namedType	= 3,
	Rename_Request__extendedObjectClass__objectClass_semaphore	= 4,
	Rename_Request__extendedObjectClass__objectClass_eventCondition	= 5,
	Rename_Request__extendedObjectClass__objectClass_eventAction	= 6,
	Rename_Request__extendedObjectClass__objectClass_eventEnrollment	= 7,
	Rename_Request__extendedObjectClass__objectClass_journal	= 8,
	Rename_Request__extendedObjectClass__objectClass_domain	= 9,
	Rename_Request__extendedObjectClass__objectClass_programInvocation	= 10,
	Rename_Request__extendedObjectClass__objectClass_operatorStation	= 11
} e_Rename_Request__extendedObjectClass__objectClass;

/* Rename-Request */
typedef struct Rename_Request {
	struct Rename_Request__extendedObjectClass {
		Rename_Request__extendedObjectClass_PR present;
		union Rename_Request__extendedObjectClass_u {
			long	 objectClass;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} extendedObjectClass;
	ObjectName_t	 currentName;
	Identifier_t	 newIdentifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Rename_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Rename_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _Rename_Request_H_ */
#include <asn_internal.h>
