/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ReportJournalStatus_Response_H_
#define	_ReportJournalStatus_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportJournalStatus-Response */
typedef struct ReportJournalStatus_Response {
	Unsigned32_t	 currentEntries;
	BOOLEAN_t	 mmsDeletable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportJournalStatus_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportJournalStatus_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportJournalStatus_Response_H_ */
#include <asn_internal.h>
