/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ReportSemaphoreStatus_Response_H_
#define	_ReportSemaphoreStatus_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include "Unsigned16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportSemaphoreStatus_Response__Class {
	ReportSemaphoreStatus_Response__class_token	= 0,
	ReportSemaphoreStatus_Response__class_pool	= 1
} e_ReportSemaphoreStatus_Response__class;

/* ReportSemaphoreStatus-Response */
typedef struct ReportSemaphoreStatus_Response {
	BOOLEAN_t	 mmsDeletable;
	long	 Class;
	Unsigned16_t	 numberOfTokens;
	Unsigned16_t	 numberOfOwnedTokens;
	Unsigned16_t	 numberOfHungTokens;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportSemaphoreStatus_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportSemaphoreStatus_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportSemaphoreStatus_Response_H_ */
#include <asn_internal.h>
