/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ReportJournalStatus_Request_H_
#define	_ReportJournalStatus_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ReportJournalStatus-Request */
typedef ObjectName_t	 ReportJournalStatus_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportJournalStatus_Request;
asn_struct_free_f ReportJournalStatus_Request_free;
asn_struct_print_f ReportJournalStatus_Request_print;
asn_constr_check_f ReportJournalStatus_Request_constraint;
ber_type_decoder_f ReportJournalStatus_Request_decode_ber;
der_type_encoder_f ReportJournalStatus_Request_encode_der;
xer_type_decoder_f ReportJournalStatus_Request_decode_xer;
xer_type_encoder_f ReportJournalStatus_Request_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportJournalStatus_Request_H_ */
#include <asn_internal.h>
