/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ReportEventEnrollmentStatus_Response_H_
#define	_ReportEventEnrollmentStatus_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Transitions.h"
#include <BOOLEAN.h>
#include "EE-Duration.h"
#include "AlarmAckRule.h"
#include "EE-State.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportEventEnrollmentStatus-Response */
typedef struct ReportEventEnrollmentStatus_Response {
	Transitions_t	 eventConditionTransitions;
	BOOLEAN_t	*notificationLost	/* DEFAULT FALSE */;
	EE_Duration_t	 duration;
	AlarmAckRule_t	*alarmAcknowledgmentRule	/* OPTIONAL */;
	EE_State_t	 currentState;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportEventEnrollmentStatus_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportEventEnrollmentStatus_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportEventEnrollmentStatus_Response_H_ */
#include <asn_internal.h>
