/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ReportedOptFlds_H_
#define	_ReportedOptFlds_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportedOptFlds {
	ReportedOptFlds_reserved	= 0,
	ReportedOptFlds_sequence_number	= 1,
	ReportedOptFlds_report_time_stamp	= 2,
	ReportedOptFlds_reason_for_inclusion	= 3,
	ReportedOptFlds_data_set_name	= 4,
	ReportedOptFlds_data_reference	= 5,
	ReportedOptFlds_buffer_overflow	= 6,
	ReportedOptFlds_entryID	= 7,
	ReportedOptFlds_conf_revision	= 8,
	ReportedOptFlds_segmentation	= 9
} e_ReportedOptFlds;

/* ReportedOptFlds */
typedef BIT_STRING_t	 ReportedOptFlds_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportedOptFlds;
asn_struct_free_f ReportedOptFlds_free;
asn_struct_print_f ReportedOptFlds_print;
asn_constr_check_f ReportedOptFlds_constraint;
ber_type_decoder_f ReportedOptFlds_decode_ber;
der_type_encoder_f ReportedOptFlds_encode_der;
xer_type_decoder_f ReportedOptFlds_decode_xer;
xer_type_encoder_f ReportedOptFlds_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportedOptFlds_H_ */
#include <asn_internal.h>
