/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Resume_Error_H_
#define	_Resume_Error_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProgramInvocationState.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Resume-Error */
typedef ProgramInvocationState_t	 Resume_Error_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Resume_Error;
asn_struct_free_f Resume_Error_free;
asn_struct_print_f Resume_Error_print;
asn_constr_check_f Resume_Error_constraint;
ber_type_decoder_f Resume_Error_decode_ber;
der_type_encoder_f Resume_Error_encode_der;
xer_type_decoder_f Resume_Error_decode_xer;
xer_type_encoder_f Resume_Error_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Resume_Error_H_ */
#include <asn_internal.h>
