/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Resume_Request_H_
#define	_Resume_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <VisibleString.h>
#include "EXTERNALt.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Resume_Request__executionArgument_PR {
	Resume_Request__executionArgument_PR_NOTHING,	/* No components present */
	Resume_Request__executionArgument_PR_simpleString,
	Resume_Request__executionArgument_PR_encodedString
} Resume_Request__executionArgument_PR;

/* Resume-Request */
typedef struct Resume_Request {
	Identifier_t	 programInvocationName;
	struct Resume_Request__executionArgument {
		Resume_Request__executionArgument_PR present;
		union Resume_Request__executionArgument_u {
			VisibleString_t	 simpleString;
			EXTERNALt_t	 encodedString;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *executionArgument;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Resume_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Resume_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _Resume_Request_H_ */
#include <asn_internal.h>
