/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SemaphoreEntry_H_
#define	_SemaphoreEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include "Identifier.h"
#include "Priority.h"
#include "Unsigned32.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SemaphoreEntry__entryClass {
	SemaphoreEntry__entryClass_simple	= 0,
	SemaphoreEntry__entryClass_modifier	= 1
} e_SemaphoreEntry__entryClass;

/* SemaphoreEntry */
typedef struct SemaphoreEntry {
	OCTET_STRING_t	 entryId;
	long	 entryClass;
	Identifier_t	*namedToken	/* OPTIONAL */;
	Priority_t	*priority	/* DEFAULT 64 */;
	Unsigned32_t	*remainingTimeOut	/* OPTIONAL */;
	BOOLEAN_t	*abortOnTimeOut	/* OPTIONAL */;
	BOOLEAN_t	*relinquishIfConnectionLost	/* DEFAULT TRUE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SemaphoreEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SemaphoreEntry;

#ifdef __cplusplus
}
#endif

#endif	/* _SemaphoreEntry_H_ */
#include <asn_internal.h>
