/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Status_Response_H_
#define	_Status_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Status_Response__vmdLogicalStatus {
	Status_Response__vmdLogicalStatus_state_changes_allowed	= 0,
	Status_Response__vmdLogicalStatus_no_state_changes_allowed	= 1,
	Status_Response__vmdLogicalStatus_limited_services_allowed	= 2,
	Status_Response__vmdLogicalStatus_support_services_allowed	= 3
} e_Status_Response__vmdLogicalStatus;
typedef enum Status_Response__vmdPhysicalStatus {
	Status_Response__vmdPhysicalStatus_operational	= 0,
	Status_Response__vmdPhysicalStatus_partially_operational	= 1,
	Status_Response__vmdPhysicalStatus_inoperable	= 2,
	Status_Response__vmdPhysicalStatus_needs_commissioning	= 3
} e_Status_Response__vmdPhysicalStatus;

/* Status-Response */
typedef struct Status_Response {
	long	 vmdLogicalStatus;
	long	 vmdPhysicalStatus;
	BIT_STRING_t	*localDetail	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Status_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Status_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _Status_Response_H_ */
#include <asn_internal.h>
