/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_TerminateDownloadSequence_Request_H_
#define	_TerminateDownloadSequence_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ServiceError;

/* TerminateDownloadSequence-Request */
typedef struct TerminateDownloadSequence_Request {
	Identifier_t	 domainName;
	struct ServiceError	*discard	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TerminateDownloadSequence_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TerminateDownloadSequence_Request;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ServiceError.h"

#endif	/* _TerminateDownloadSequence_Request_H_ */
#include <asn_internal.h>
