/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_TriggerEvent_Request_H_
#define	_TriggerEvent_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include "Priority.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TriggerEvent-Request */
typedef struct TriggerEvent_Request {
	ObjectName_t	 eventConditionName;
	Priority_t	*priority	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TriggerEvent_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TriggerEvent_Request;

#ifdef __cplusplus
}
#endif

#endif	/* _TriggerEvent_Request_H_ */
#include <asn_internal.h>
