/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../../../../utils/mms-simple.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_TypeSpecification_H_
#define	_TypeSpecification_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "Integer32.h"
#include "Unsigned8.h"
#include <BOOLEAN.h>
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TypeSpecification_PR {
	TypeSpecification_PR_NOTHING,	/* No components present */
	TypeSpecification_PR_array,
	TypeSpecification_PR_structure,
	TypeSpecification_PR_boolean,
	TypeSpecification_PR_bitString,
	TypeSpecification_PR_integer,
	TypeSpecification_PR_unsigned,
	TypeSpecification_PR_floatingPoint,
	TypeSpecification_PR_octetString,
	TypeSpecification_PR_visibleString,
	TypeSpecification_PR_binaryTime,
	TypeSpecification_PR_mmsString,
	TypeSpecification_PR_utcTime
} TypeSpecification_PR;

/* Forward declarations */
struct TypeSpecification;
struct StructComponent;

/* TypeSpecification */
typedef struct TypeSpecification {
	TypeSpecification_PR present;
	union TypeSpecification_u {
		struct TypeSpecification__array {
			BOOLEAN_t	*packed	/* DEFAULT FALSE */;
			Unsigned32_t	 numberOfElements;
			struct TypeSpecification	*elementType;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} array;
		struct TypeSpecification__structure {
			BOOLEAN_t	*packed	/* DEFAULT FALSE */;
			struct TypeSpecification__structure__components {
				A_SEQUENCE_OF(struct StructComponent) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} components;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} structure;
		NULL_t	 boolean;
		Integer32_t	 bitString;
		Unsigned8_t	 integer;
		Unsigned8_t	 Unsigned;
		struct TypeSpecification__floatingPoint {
			Unsigned8_t	 formatWidth;
			Unsigned8_t	 exponentWidth;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} floatingPoint;
		Integer32_t	 octetString;
		Integer32_t	 visibleString;
		BOOLEAN_t	 binaryTime;
		Integer32_t	 mmsString;
		NULL_t	 utcTime;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TypeSpecification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TypeSpecification;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TypeSpecification.h"
#include "StructComponent.h"

#endif	/* _TypeSpecification_H_ */
#include <asn_internal.h>
