/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#include "TypeSpecification.h"

static asn_TYPE_member_t asn_MBR_array_3[] = {
	{ ATF_POINTER, 1, offsetof(struct TypeSpecification__array, packed),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"packed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification__array, numberOfElements),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfElements"
		},
	{ ATF_POINTER, 0, offsetof(struct TypeSpecification__array, elementType),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TypeSpecification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"elementType"
		},
};
static const ber_tlv_tag_t asn_DEF_array_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_array_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* packed */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numberOfElements */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* elementType */
};
static asn_SEQUENCE_specifics_t asn_SPC_array_specs_3 = {
	sizeof(struct TypeSpecification__array),
	offsetof(struct TypeSpecification__array, _asn_ctx),
	asn_MAP_array_tag2el_3,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_array_3 = {
	"array",
	"array",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_array_tags_3,
	sizeof(asn_DEF_array_tags_3)
		/sizeof(asn_DEF_array_tags_3[0]) - 1, /* 1 */
	asn_DEF_array_tags_3,	/* Same as above */
	sizeof(asn_DEF_array_tags_3)
		/sizeof(asn_DEF_array_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_array_3,
	3,	/* Elements count */
	&asn_SPC_array_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_10[] = {
	{ ATF_POINTER, 1, offsetof(struct TypeSpecification__structure__components__Member, componentName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"componentName"
		},
	{ ATF_POINTER, 0, offsetof(struct TypeSpecification__structure__components__Member, componentType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TypeSpecification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"componentType"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* componentName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* componentType */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_10 = {
	sizeof(struct TypeSpecification__structure__components__Member),
	offsetof(struct TypeSpecification__structure__components__Member, _asn_ctx),
	asn_MAP_Member_tag2el_10,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_10 = {
	"SEQUENCE",
	"SEQUENCE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Member_tags_10,
	sizeof(asn_DEF_Member_tags_10)
		/sizeof(asn_DEF_Member_tags_10[0]), /* 1 */
	asn_DEF_Member_tags_10,	/* Same as above */
	sizeof(asn_DEF_Member_tags_10)
		/sizeof(asn_DEF_Member_tags_10[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Member_10,
	2,	/* Elements count */
	&asn_SPC_Member_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_components_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_components_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_components_specs_9 = {
	sizeof(struct TypeSpecification__structure__components),
	offsetof(struct TypeSpecification__structure__components, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_components_9 = {
	"components",
	"components",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_components_tags_9,
	sizeof(asn_DEF_components_tags_9)
		/sizeof(asn_DEF_components_tags_9[0]) - 1, /* 1 */
	asn_DEF_components_tags_9,	/* Same as above */
	sizeof(asn_DEF_components_tags_9)
		/sizeof(asn_DEF_components_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_components_9,
	1,	/* Single element */
	&asn_SPC_components_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_structure_7[] = {
	{ ATF_POINTER, 1, offsetof(struct TypeSpecification__structure, packed),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"packed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification__structure, components),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_components_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"components"
		},
};
static const ber_tlv_tag_t asn_DEF_structure_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_structure_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* packed */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* components */
};
static asn_SEQUENCE_specifics_t asn_SPC_structure_specs_7 = {
	sizeof(struct TypeSpecification__structure),
	offsetof(struct TypeSpecification__structure, _asn_ctx),
	asn_MAP_structure_tag2el_7,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_structure_7 = {
	"structure",
	"structure",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_structure_tags_7,
	sizeof(asn_DEF_structure_tags_7)
		/sizeof(asn_DEF_structure_tags_7[0]) - 1, /* 1 */
	asn_DEF_structure_tags_7,	/* Same as above */
	sizeof(asn_DEF_structure_tags_7)
		/sizeof(asn_DEF_structure_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_structure_7,
	2,	/* Elements count */
	&asn_SPC_structure_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_TypeSpecification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.typeName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"typeName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.array),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_array_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"array"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.structure),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_structure_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"structure"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.boolean),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"boolean"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.bit_string),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bit-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.integer),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"integer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.Unsigned),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unsigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.octet_string),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octet-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.visible_string),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"visible-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.generalized_time),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"generalized-time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.binary_time),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"binary-time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.bcd),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bcd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.objId),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"objId"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TypeSpecification_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* typeName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* array */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* structure */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* boolean */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* bit-string */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 7, 0, 0 }, /* octet-string */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 8, 0, 0 }, /* visible-string */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 9, 0, 0 }, /* generalized-time */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 10, 0, 0 }, /* binary-time */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 11, 0, 0 }, /* bcd */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 12, 0, 0 } /* objId */
};
static asn_CHOICE_specifics_t asn_SPC_TypeSpecification_specs_1 = {
	sizeof(struct TypeSpecification),
	offsetof(struct TypeSpecification, _asn_ctx),
	offsetof(struct TypeSpecification, present),
	sizeof(((struct TypeSpecification *)0)->present),
	asn_MAP_TypeSpecification_tag2el_1,
	13,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TypeSpecification = {
	"TypeSpecification",
	"TypeSpecification",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_TypeSpecification_1,
	13,	/* Elements count */
	&asn_SPC_TypeSpecification_specs_1	/* Additional specs */
};

