/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_TypeSpecification_H_
#define	_TypeSpecification_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include <NULL.h>
#include "Integer32.h"
#include "Unsigned8.h"
#include <BOOLEAN.h>
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include "Identifier.h"
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TypeSpecification_PR {
	TypeSpecification_PR_NOTHING,	/* No components present */
	TypeSpecification_PR_typeName,
	TypeSpecification_PR_array,
	TypeSpecification_PR_structure,
	TypeSpecification_PR_boolean,
	TypeSpecification_PR_bit_string,
	TypeSpecification_PR_integer,
	TypeSpecification_PR_unsigned,
	TypeSpecification_PR_octet_string,
	TypeSpecification_PR_visible_string,
	TypeSpecification_PR_generalized_time,
	TypeSpecification_PR_binary_time,
	TypeSpecification_PR_bcd,
	TypeSpecification_PR_objId
} TypeSpecification_PR;

/* Forward declarations */
struct TypeSpecification;

/* TypeSpecification */
typedef struct TypeSpecification {
	TypeSpecification_PR present;
	union TypeSpecification_u {
		ObjectName_t	 typeName;
		struct TypeSpecification__array {
			BOOLEAN_t	*packed	/* DEFAULT FALSE */;
			Unsigned32_t	 numberOfElements;
			struct TypeSpecification	*elementType;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} array;
		struct TypeSpecification__structure {
			BOOLEAN_t	*packed	/* DEFAULT FALSE */;
			struct TypeSpecification__structure__components {
				A_SEQUENCE_OF(struct TypeSpecification__structure__components__Member {
					Identifier_t	*componentName	/* OPTIONAL */;
					struct TypeSpecification	*componentType;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} ) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} components;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} structure;
		NULL_t	 boolean;
		Integer32_t	 bit_string;
		Unsigned8_t	 integer;
		Unsigned8_t	 Unsigned;
		Integer32_t	 octet_string;
		Integer32_t	 visible_string;
		NULL_t	 generalized_time;
		BOOLEAN_t	 binary_time;
		Unsigned8_t	 bcd;
		NULL_t	 objId;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TypeSpecification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TypeSpecification;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TypeSpecification.h"

#endif	/* _TypeSpecification_H_ */
#include <asn_internal.h>
