/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../../../../utils/mms-simple.asn"
 * 	`asn1c -fcompound-names`
 */

#include "TypeSpecification.h"

static asn_TYPE_member_t asn_MBR_array_2[] = {
	{ ATF_POINTER, 1, offsetof(struct TypeSpecification__array, packed),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"packed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification__array, numberOfElements),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfElements"
		},
	{ ATF_POINTER, 0, offsetof(struct TypeSpecification__array, elementType),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TypeSpecification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"elementType"
		},
};
static const ber_tlv_tag_t asn_DEF_array_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_array_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* packed */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numberOfElements */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* elementType */
};
static asn_SEQUENCE_specifics_t asn_SPC_array_specs_2 = {
	sizeof(struct TypeSpecification__array),
	offsetof(struct TypeSpecification__array, _asn_ctx),
	asn_MAP_array_tag2el_2,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_array_2 = {
	"array",
	"array",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_array_tags_2,
	sizeof(asn_DEF_array_tags_2)
		/sizeof(asn_DEF_array_tags_2[0]) - 1, /* 1 */
	asn_DEF_array_tags_2,	/* Same as above */
	sizeof(asn_DEF_array_tags_2)
		/sizeof(asn_DEF_array_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_array_2,
	3,	/* Elements count */
	&asn_SPC_array_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_components_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StructComponent,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_components_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_components_specs_8 = {
	sizeof(struct TypeSpecification__structure__components),
	offsetof(struct TypeSpecification__structure__components, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_components_8 = {
	"components",
	"components",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_components_tags_8,
	sizeof(asn_DEF_components_tags_8)
		/sizeof(asn_DEF_components_tags_8[0]) - 1, /* 1 */
	asn_DEF_components_tags_8,	/* Same as above */
	sizeof(asn_DEF_components_tags_8)
		/sizeof(asn_DEF_components_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_components_8,
	1,	/* Single element */
	&asn_SPC_components_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_structure_6[] = {
	{ ATF_POINTER, 1, offsetof(struct TypeSpecification__structure, packed),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"packed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification__structure, components),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_components_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"components"
		},
};
static const ber_tlv_tag_t asn_DEF_structure_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_structure_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* packed */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* components */
};
static asn_SEQUENCE_specifics_t asn_SPC_structure_specs_6 = {
	sizeof(struct TypeSpecification__structure),
	offsetof(struct TypeSpecification__structure, _asn_ctx),
	asn_MAP_structure_tag2el_6,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_structure_6 = {
	"structure",
	"structure",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_structure_tags_6,
	sizeof(asn_DEF_structure_tags_6)
		/sizeof(asn_DEF_structure_tags_6[0]) - 1, /* 1 */
	asn_DEF_structure_tags_6,	/* Same as above */
	sizeof(asn_DEF_structure_tags_6)
		/sizeof(asn_DEF_structure_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_structure_6,
	2,	/* Elements count */
	&asn_SPC_structure_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_floatingPoint_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification__floatingPoint, formatWidth),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"formatWidth"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification__floatingPoint, exponentWidth),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"exponentWidth"
		},
};
static const ber_tlv_tag_t asn_DEF_floatingPoint_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_floatingPoint_tag2el_14[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* formatWidth */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* exponentWidth */
};
static asn_SEQUENCE_specifics_t asn_SPC_floatingPoint_specs_14 = {
	sizeof(struct TypeSpecification__floatingPoint),
	offsetof(struct TypeSpecification__floatingPoint, _asn_ctx),
	asn_MAP_floatingPoint_tag2el_14,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_floatingPoint_14 = {
	"floatingPoint",
	"floatingPoint",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_floatingPoint_tags_14,
	sizeof(asn_DEF_floatingPoint_tags_14)
		/sizeof(asn_DEF_floatingPoint_tags_14[0]) - 1, /* 1 */
	asn_DEF_floatingPoint_tags_14,	/* Same as above */
	sizeof(asn_DEF_floatingPoint_tags_14)
		/sizeof(asn_DEF_floatingPoint_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_floatingPoint_14,
	2,	/* Elements count */
	&asn_SPC_floatingPoint_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_TypeSpecification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.array),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_array_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"array"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.structure),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_structure_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"structure"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.boolean),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"boolean"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.bitString),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.integer),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"integer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.Unsigned),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Unsigned8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unsigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.floatingPoint),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_floatingPoint_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"floatingPoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.octetString),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octetString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.visibleString),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"visibleString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.binaryTime),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"binaryTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.mmsString),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mmsString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TypeSpecification, choice.utcTime),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"utcTime"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TypeSpecification_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* array */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* structure */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* boolean */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* bitString */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* unsigned */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* floatingPoint */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 7, 0, 0 }, /* octetString */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 8, 0, 0 }, /* visibleString */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 9, 0, 0 }, /* binaryTime */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 10, 0, 0 }, /* mmsString */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 11, 0, 0 } /* utcTime */
};
static asn_CHOICE_specifics_t asn_SPC_TypeSpecification_specs_1 = {
	sizeof(struct TypeSpecification),
	offsetof(struct TypeSpecification, _asn_ctx),
	offsetof(struct TypeSpecification, present),
	sizeof(((struct TypeSpecification *)0)->present),
	asn_MAP_TypeSpecification_tag2el_1,
	12,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TypeSpecification = {
	"TypeSpecification",
	"TypeSpecification",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_TypeSpecification_1,
	12,	/* Elements count */
	&asn_SPC_TypeSpecification_specs_1	/* Additional specs */
};

