/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Unconfirmed_PDU_H_
#define	_Unconfirmed_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UnconfirmedService.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CS_Request_Detail;

/* Unconfirmed-PDU */
typedef struct Unconfirmed_PDU {
	UnconfirmedService_t	 unconfirmedService;
	struct CS_Request_Detail	*cs_request_detail	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Unconfirmed_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Unconfirmed_PDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CS-Request-Detail.h"

#endif	/* _Unconfirmed_PDU_H_ */
#include <asn_internal.h>
