/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_UnsolicitedStatus_H_
#define	_UnsolicitedStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Status-Response.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UnsolicitedStatus */
typedef Status_Response_t	 UnsolicitedStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnsolicitedStatus;
asn_struct_free_f UnsolicitedStatus_free;
asn_struct_print_f UnsolicitedStatus_print;
asn_constr_check_f UnsolicitedStatus_constraint;
ber_type_decoder_f UnsolicitedStatus_decode_ber;
der_type_encoder_f UnsolicitedStatus_encode_der;
xer_type_decoder_f UnsolicitedStatus_decode_xer;
xer_type_encoder_f UnsolicitedStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UnsolicitedStatus_H_ */
#include <asn_internal.h>
