/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_UploadSegment_Response_H_
#define	_UploadSegment_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <OCTET_STRING.h>
#include "EXTERNALt.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UploadSegment_Response__loadData_PR {
	UploadSegment_Response__loadData_PR_NOTHING,	/* No components present */
	UploadSegment_Response__loadData_PR_non_coded,
	UploadSegment_Response__loadData_PR_coded
} UploadSegment_Response__loadData_PR;

/* UploadSegment-Response */
typedef struct UploadSegment_Response {
	struct UploadSegment_Response__loadData {
		UploadSegment_Response__loadData_PR present;
		union UploadSegment_Response__loadData_u {
			OCTET_STRING_t	 non_coded;
			EXTERNALt_t	 coded;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} loadData;
	BOOLEAN_t	*moreFollows	/* DEFAULT TRUE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UploadSegment_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UploadSegment_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _UploadSegment_Response_H_ */
#include <asn_internal.h>
