/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../../../../utils/mms-simple.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VariableSpecification_H_
#define	_VariableSpecification_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VariableSpecification_PR {
	VariableSpecification_PR_NOTHING,	/* No components present */
	VariableSpecification_PR_name
} VariableSpecification_PR;

/* VariableSpecification */
typedef struct VariableSpecification {
	VariableSpecification_PR present;
	union VariableSpecification_u {
		ObjectName_t	 name;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VariableSpecification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VariableSpecification;

#ifdef __cplusplus
}
#endif

#endif	/* _VariableSpecification_H_ */
#include <asn_internal.h>
