/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../../../../utils/mms-simple.asn"
 * 	`asn1c -fcompound-names`
 */

#include "VariableSpecification.h"

static asn_TYPE_member_t asn_MBR_VariableSpecification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VariableSpecification, choice.name),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_VariableSpecification_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* name */
};
static asn_CHOICE_specifics_t asn_SPC_VariableSpecification_specs_1 = {
	sizeof(struct VariableSpecification),
	offsetof(struct VariableSpecification, _asn_ctx),
	offsetof(struct VariableSpecification, present),
	sizeof(((struct VariableSpecification *)0)->present),
	asn_MAP_VariableSpecification_tag2el_1,
	1,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_VariableSpecification = {
	"VariableSpecification",
	"VariableSpecification",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_VariableSpecification_1,
	1,	/* Elements count */
	&asn_SPC_VariableSpecification_specs_1	/* Additional specs */
};

